// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PAppRequest.proto

package com.argo.sdk.protobuf;

/**
 * Protobuf type {@code PAppRequestParam}
 */
public  final class PAppRequestParam extends
    com.google.protobuf.GeneratedMessage
    implements PAppRequestParamOrBuilder {
  // Use PAppRequestParam.newBuilder() to construct.
  private PAppRequestParam(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
    this.unknownFields = builder.getUnknownFields();
  }
  private PAppRequestParam(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

  private static final PAppRequestParam defaultInstance;
  public static PAppRequestParam getDefaultInstance() {
    return defaultInstance;
  }

  public PAppRequestParam getDefaultInstanceForType() {
    return defaultInstance;
  }

  private final com.google.protobuf.UnknownFieldSet unknownFields;
  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
    return this.unknownFields;
  }
  private PAppRequestParam(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    initFields();
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownField(input, unknownFields,
                                   extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            bitField0_ |= 0x00000001;
            name_ = input.readBytes();
            break;
          }
          case 16: {
            bitField0_ |= 0x00000002;
            intValue_ = input.readInt32();
            break;
          }
          case 26: {
            bitField0_ |= 0x00000004;
            strValue_ = input.readBytes();
            break;
          }
          case 32: {
            bitField0_ |= 0x00000008;
            longValue_ = input.readInt64();
            break;
          }
          case 45: {
            bitField0_ |= 0x00000010;
            floatValue_ = input.readFloat();
            break;
          }
          case 48: {
            bitField0_ |= 0x00000020;
            boolValue_ = input.readBool();
            break;
          }
          case 58: {
            bitField0_ |= 0x00000040;
            bytesValue_ = input.readBytes();
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e.getMessage()).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.argo.sdk.protobuf.PAppRequestProto.internal_static_PAppRequestParam_descriptor;
  }

  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.argo.sdk.protobuf.PAppRequestProto.internal_static_PAppRequestParam_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.argo.sdk.protobuf.PAppRequestParam.class, com.argo.sdk.protobuf.PAppRequestParam.Builder.class);
  }

  public static com.google.protobuf.Parser<PAppRequestParam> PARSER =
      new com.google.protobuf.AbstractParser<PAppRequestParam>() {
    public PAppRequestParam parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new PAppRequestParam(input, extensionRegistry);
    }
  };

  @java.lang.Override
  public com.google.protobuf.Parser<PAppRequestParam> getParserForType() {
    return PARSER;
  }

  private int bitField0_;
  // required string name = 1;
  public static final int NAME_FIELD_NUMBER = 1;
  private java.lang.Object name_;
  /**
   * <code>required string name = 1;</code>
   */
  public boolean hasName() {
    return ((bitField0_ & 0x00000001) == 0x00000001);
  }
  /**
   * <code>required string name = 1;</code>
   */
  public java.lang.String getName() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        name_ = s;
      }
      return s;
    }
  }
  /**
   * <code>required string name = 1;</code>
   */
  public com.google.protobuf.ByteString
      getNameBytes() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      name_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  // optional int32 intValue = 2;
  public static final int INTVALUE_FIELD_NUMBER = 2;
  private int intValue_;
  /**
   * <code>optional int32 intValue = 2;</code>
   */
  public boolean hasIntValue() {
    return ((bitField0_ & 0x00000002) == 0x00000002);
  }
  /**
   * <code>optional int32 intValue = 2;</code>
   */
  public int getIntValue() {
    return intValue_;
  }

  // optional string strValue = 3;
  public static final int STRVALUE_FIELD_NUMBER = 3;
  private java.lang.Object strValue_;
  /**
   * <code>optional string strValue = 3;</code>
   */
  public boolean hasStrValue() {
    return ((bitField0_ & 0x00000004) == 0x00000004);
  }
  /**
   * <code>optional string strValue = 3;</code>
   */
  public java.lang.String getStrValue() {
    java.lang.Object ref = strValue_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        strValue_ = s;
      }
      return s;
    }
  }
  /**
   * <code>optional string strValue = 3;</code>
   */
  public com.google.protobuf.ByteString
      getStrValueBytes() {
    java.lang.Object ref = strValue_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      strValue_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  // optional int64 longValue = 4;
  public static final int LONGVALUE_FIELD_NUMBER = 4;
  private long longValue_;
  /**
   * <code>optional int64 longValue = 4;</code>
   */
  public boolean hasLongValue() {
    return ((bitField0_ & 0x00000008) == 0x00000008);
  }
  /**
   * <code>optional int64 longValue = 4;</code>
   */
  public long getLongValue() {
    return longValue_;
  }

  // optional float floatValue = 5;
  public static final int FLOATVALUE_FIELD_NUMBER = 5;
  private float floatValue_;
  /**
   * <code>optional float floatValue = 5;</code>
   */
  public boolean hasFloatValue() {
    return ((bitField0_ & 0x00000010) == 0x00000010);
  }
  /**
   * <code>optional float floatValue = 5;</code>
   */
  public float getFloatValue() {
    return floatValue_;
  }

  // optional bool boolValue = 6;
  public static final int BOOLVALUE_FIELD_NUMBER = 6;
  private boolean boolValue_;
  /**
   * <code>optional bool boolValue = 6;</code>
   */
  public boolean hasBoolValue() {
    return ((bitField0_ & 0x00000020) == 0x00000020);
  }
  /**
   * <code>optional bool boolValue = 6;</code>
   */
  public boolean getBoolValue() {
    return boolValue_;
  }

  // optional bytes bytesValue = 7;
  public static final int BYTESVALUE_FIELD_NUMBER = 7;
  private com.google.protobuf.ByteString bytesValue_;
  /**
   * <code>optional bytes bytesValue = 7;</code>
   */
  public boolean hasBytesValue() {
    return ((bitField0_ & 0x00000040) == 0x00000040);
  }
  /**
   * <code>optional bytes bytesValue = 7;</code>
   */
  public com.google.protobuf.ByteString getBytesValue() {
    return bytesValue_;
  }

  private void initFields() {
    name_ = "";
    intValue_ = 0;
    strValue_ = "";
    longValue_ = 0L;
    floatValue_ = 0F;
    boolValue_ = false;
    bytesValue_ = com.google.protobuf.ByteString.EMPTY;
  }
  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized != -1) return isInitialized == 1;

    if (!hasName()) {
      memoizedIsInitialized = 0;
      return false;
    }
    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    getSerializedSize();
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      output.writeBytes(1, getNameBytes());
    }
    if (((bitField0_ & 0x00000002) == 0x00000002)) {
      output.writeInt32(2, intValue_);
    }
    if (((bitField0_ & 0x00000004) == 0x00000004)) {
      output.writeBytes(3, getStrValueBytes());
    }
    if (((bitField0_ & 0x00000008) == 0x00000008)) {
      output.writeInt64(4, longValue_);
    }
    if (((bitField0_ & 0x00000010) == 0x00000010)) {
      output.writeFloat(5, floatValue_);
    }
    if (((bitField0_ & 0x00000020) == 0x00000020)) {
      output.writeBool(6, boolValue_);
    }
    if (((bitField0_ & 0x00000040) == 0x00000040)) {
      output.writeBytes(7, bytesValue_);
    }
    getUnknownFields().writeTo(output);
  }

  private int memoizedSerializedSize = -1;
  public int getSerializedSize() {
    int size = memoizedSerializedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(1, getNameBytes());
    }
    if (((bitField0_ & 0x00000002) == 0x00000002)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, intValue_);
    }
    if (((bitField0_ & 0x00000004) == 0x00000004)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(3, getStrValueBytes());
    }
    if (((bitField0_ & 0x00000008) == 0x00000008)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(4, longValue_);
    }
    if (((bitField0_ & 0x00000010) == 0x00000010)) {
      size += com.google.protobuf.CodedOutputStream
        .computeFloatSize(5, floatValue_);
    }
    if (((bitField0_ & 0x00000020) == 0x00000020)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(6, boolValue_);
    }
    if (((bitField0_ & 0x00000040) == 0x00000040)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(7, bytesValue_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSerializedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  protected java.lang.Object writeReplace()
      throws java.io.ObjectStreamException {
    return super.writeReplace();
  }

  public static com.argo.sdk.protobuf.PAppRequestParam parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.argo.sdk.protobuf.PAppRequestParam parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.argo.sdk.protobuf.PAppRequestParam parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.argo.sdk.protobuf.PAppRequestParam parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.argo.sdk.protobuf.PAppRequestParam parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static com.argo.sdk.protobuf.PAppRequestParam parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }
  public static com.argo.sdk.protobuf.PAppRequestParam parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input);
  }
  public static com.argo.sdk.protobuf.PAppRequestParam parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input, extensionRegistry);
  }
  public static com.argo.sdk.protobuf.PAppRequestParam parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static com.argo.sdk.protobuf.PAppRequestParam parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }

  public static Builder newBuilder() { return Builder.create(); }
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder(com.argo.sdk.protobuf.PAppRequestParam prototype) {
    return newBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() { return newBuilder(this); }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code PAppRequestParam}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder>
     implements com.argo.sdk.protobuf.PAppRequestParamOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.argo.sdk.protobuf.PAppRequestProto.internal_static_PAppRequestParam_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.argo.sdk.protobuf.PAppRequestProto.internal_static_PAppRequestParam_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.argo.sdk.protobuf.PAppRequestParam.class, com.argo.sdk.protobuf.PAppRequestParam.Builder.class);
    }

    // Construct using com.argo.sdk.protobuf.PAppRequestParam.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
      }
    }
    private static Builder create() {
      return new Builder();
    }

    public Builder clear() {
      super.clear();
      name_ = "";
      bitField0_ = (bitField0_ & ~0x00000001);
      intValue_ = 0;
      bitField0_ = (bitField0_ & ~0x00000002);
      strValue_ = "";
      bitField0_ = (bitField0_ & ~0x00000004);
      longValue_ = 0L;
      bitField0_ = (bitField0_ & ~0x00000008);
      floatValue_ = 0F;
      bitField0_ = (bitField0_ & ~0x00000010);
      boolValue_ = false;
      bitField0_ = (bitField0_ & ~0x00000020);
      bytesValue_ = com.google.protobuf.ByteString.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000040);
      return this;
    }

    public Builder clone() {
      return create().mergeFrom(buildPartial());
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.argo.sdk.protobuf.PAppRequestProto.internal_static_PAppRequestParam_descriptor;
    }

    public com.argo.sdk.protobuf.PAppRequestParam getDefaultInstanceForType() {
      return com.argo.sdk.protobuf.PAppRequestParam.getDefaultInstance();
    }

    public com.argo.sdk.protobuf.PAppRequestParam build() {
      com.argo.sdk.protobuf.PAppRequestParam result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.argo.sdk.protobuf.PAppRequestParam buildPartial() {
      com.argo.sdk.protobuf.PAppRequestParam result = new com.argo.sdk.protobuf.PAppRequestParam(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
        to_bitField0_ |= 0x00000001;
      }
      result.name_ = name_;
      if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
        to_bitField0_ |= 0x00000002;
      }
      result.intValue_ = intValue_;
      if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
        to_bitField0_ |= 0x00000004;
      }
      result.strValue_ = strValue_;
      if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
        to_bitField0_ |= 0x00000008;
      }
      result.longValue_ = longValue_;
      if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
        to_bitField0_ |= 0x00000010;
      }
      result.floatValue_ = floatValue_;
      if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
        to_bitField0_ |= 0x00000020;
      }
      result.boolValue_ = boolValue_;
      if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
        to_bitField0_ |= 0x00000040;
      }
      result.bytesValue_ = bytesValue_;
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.argo.sdk.protobuf.PAppRequestParam) {
        return mergeFrom((com.argo.sdk.protobuf.PAppRequestParam)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.argo.sdk.protobuf.PAppRequestParam other) {
      if (other == com.argo.sdk.protobuf.PAppRequestParam.getDefaultInstance()) return this;
      if (other.hasName()) {
        bitField0_ |= 0x00000001;
        name_ = other.name_;
        onChanged();
      }
      if (other.hasIntValue()) {
        setIntValue(other.getIntValue());
      }
      if (other.hasStrValue()) {
        bitField0_ |= 0x00000004;
        strValue_ = other.strValue_;
        onChanged();
      }
      if (other.hasLongValue()) {
        setLongValue(other.getLongValue());
      }
      if (other.hasFloatValue()) {
        setFloatValue(other.getFloatValue());
      }
      if (other.hasBoolValue()) {
        setBoolValue(other.getBoolValue());
      }
      if (other.hasBytesValue()) {
        setBytesValue(other.getBytesValue());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      return this;
    }

    public final boolean isInitialized() {
      if (!hasName()) {
        
        return false;
      }
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.argo.sdk.protobuf.PAppRequestParam parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.argo.sdk.protobuf.PAppRequestParam) e.getUnfinishedMessage();
        throw e;
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    // required string name = 1;
    private java.lang.Object name_ = "";
    /**
     * <code>required string name = 1;</code>
     */
    public boolean hasName() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string name = 1;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (!(ref instanceof java.lang.String)) {
        java.lang.String s = ((com.google.protobuf.ByteString) ref)
            .toStringUtf8();
        name_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>required string name = 1;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>required string name = 1;</code>
     */
    public Builder setName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
      name_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>required string name = 1;</code>
     */
    public Builder clearName() {
      bitField0_ = (bitField0_ & ~0x00000001);
      name_ = getDefaultInstance().getName();
      onChanged();
      return this;
    }
    /**
     * <code>required string name = 1;</code>
     */
    public Builder setNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
      name_ = value;
      onChanged();
      return this;
    }

    // optional int32 intValue = 2;
    private int intValue_ ;
    /**
     * <code>optional int32 intValue = 2;</code>
     */
    public boolean hasIntValue() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional int32 intValue = 2;</code>
     */
    public int getIntValue() {
      return intValue_;
    }
    /**
     * <code>optional int32 intValue = 2;</code>
     */
    public Builder setIntValue(int value) {
      bitField0_ |= 0x00000002;
      intValue_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional int32 intValue = 2;</code>
     */
    public Builder clearIntValue() {
      bitField0_ = (bitField0_ & ~0x00000002);
      intValue_ = 0;
      onChanged();
      return this;
    }

    // optional string strValue = 3;
    private java.lang.Object strValue_ = "";
    /**
     * <code>optional string strValue = 3;</code>
     */
    public boolean hasStrValue() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional string strValue = 3;</code>
     */
    public java.lang.String getStrValue() {
      java.lang.Object ref = strValue_;
      if (!(ref instanceof java.lang.String)) {
        java.lang.String s = ((com.google.protobuf.ByteString) ref)
            .toStringUtf8();
        strValue_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string strValue = 3;</code>
     */
    public com.google.protobuf.ByteString
        getStrValueBytes() {
      java.lang.Object ref = strValue_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        strValue_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string strValue = 3;</code>
     */
    public Builder setStrValue(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
      strValue_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string strValue = 3;</code>
     */
    public Builder clearStrValue() {
      bitField0_ = (bitField0_ & ~0x00000004);
      strValue_ = getDefaultInstance().getStrValue();
      onChanged();
      return this;
    }
    /**
     * <code>optional string strValue = 3;</code>
     */
    public Builder setStrValueBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
      strValue_ = value;
      onChanged();
      return this;
    }

    // optional int64 longValue = 4;
    private long longValue_ ;
    /**
     * <code>optional int64 longValue = 4;</code>
     */
    public boolean hasLongValue() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional int64 longValue = 4;</code>
     */
    public long getLongValue() {
      return longValue_;
    }
    /**
     * <code>optional int64 longValue = 4;</code>
     */
    public Builder setLongValue(long value) {
      bitField0_ |= 0x00000008;
      longValue_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional int64 longValue = 4;</code>
     */
    public Builder clearLongValue() {
      bitField0_ = (bitField0_ & ~0x00000008);
      longValue_ = 0L;
      onChanged();
      return this;
    }

    // optional float floatValue = 5;
    private float floatValue_ ;
    /**
     * <code>optional float floatValue = 5;</code>
     */
    public boolean hasFloatValue() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional float floatValue = 5;</code>
     */
    public float getFloatValue() {
      return floatValue_;
    }
    /**
     * <code>optional float floatValue = 5;</code>
     */
    public Builder setFloatValue(float value) {
      bitField0_ |= 0x00000010;
      floatValue_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional float floatValue = 5;</code>
     */
    public Builder clearFloatValue() {
      bitField0_ = (bitField0_ & ~0x00000010);
      floatValue_ = 0F;
      onChanged();
      return this;
    }

    // optional bool boolValue = 6;
    private boolean boolValue_ ;
    /**
     * <code>optional bool boolValue = 6;</code>
     */
    public boolean hasBoolValue() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>optional bool boolValue = 6;</code>
     */
    public boolean getBoolValue() {
      return boolValue_;
    }
    /**
     * <code>optional bool boolValue = 6;</code>
     */
    public Builder setBoolValue(boolean value) {
      bitField0_ |= 0x00000020;
      boolValue_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional bool boolValue = 6;</code>
     */
    public Builder clearBoolValue() {
      bitField0_ = (bitField0_ & ~0x00000020);
      boolValue_ = false;
      onChanged();
      return this;
    }

    // optional bytes bytesValue = 7;
    private com.google.protobuf.ByteString bytesValue_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>optional bytes bytesValue = 7;</code>
     */
    public boolean hasBytesValue() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>optional bytes bytesValue = 7;</code>
     */
    public com.google.protobuf.ByteString getBytesValue() {
      return bytesValue_;
    }
    /**
     * <code>optional bytes bytesValue = 7;</code>
     */
    public Builder setBytesValue(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
      bytesValue_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional bytes bytesValue = 7;</code>
     */
    public Builder clearBytesValue() {
      bitField0_ = (bitField0_ & ~0x00000040);
      bytesValue_ = getDefaultInstance().getBytesValue();
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:PAppRequestParam)
  }

  static {
    defaultInstance = new PAppRequestParam(true);
    defaultInstance.initFields();
  }

  // @@protoc_insertion_point(class_scope:PAppRequestParam)
}

