// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PAppRequest.proto

package com.argo.sdk.protobuf;

public final class PAppRequestProto {
  private PAppRequestProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  static com.google.protobuf.Descriptors.Descriptor
    internal_static_PAppRequestParam_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_PAppRequestParam_fieldAccessorTable;
  static com.google.protobuf.Descriptors.Descriptor
    internal_static_PAppRequest_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_PAppRequest_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021PAppRequest.proto\"\222\001\n\020PAppRequestParam" +
      "\022\014\n\004name\030\001 \002(\t\022\020\n\010intValue\030\002 \001(\005\022\020\n\010strV" +
      "alue\030\003 \001(\t\022\021\n\tlongValue\030\004 \001(\003\022\022\n\nfloatVa" +
      "lue\030\005 \001(\002\022\021\n\tboolValue\030\006 \001(\010\022\022\n\nbytesVal" +
      "ue\030\007 \001(\014\"\241\001\n\013PAppRequest\022\016\n\006authId\030\001 \002(\t" +
      "\022\021\n\tsessionId\030\002 \001(\t\022\017\n\007version\030\003 \001(\005\022\014\n\004" +
      "sign\030\004 \001(\t\022\r\n\005nonce\030\005 \001(\t\022\021\n\tuserAgent\030\006" +
      " \001(\t\022\014\n\004path\030\007 \001(\t\022 \n\005param\030\010 \003(\0132\021.PApp" +
      "RequestParamB+\n\025com.argo.sdk.protobufB\020P" +
      "AppRequestProtoP\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_PAppRequestParam_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_PAppRequestParam_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_PAppRequestParam_descriptor,
              new java.lang.String[] { "Name", "IntValue", "StrValue", "LongValue", "FloatValue", "BoolValue", "BytesValue", });
          internal_static_PAppRequest_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_PAppRequest_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_PAppRequest_descriptor,
              new java.lang.String[] { "AuthId", "SessionId", "Version", "Sign", "Nonce", "UserAgent", "Path", "Param", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
