// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PAppRequest.proto

package com.argo.sdk.protobuf;

/**
 * Protobuf type {@code PAppRequest}
 */
public  final class PAppRequest extends
    com.google.protobuf.GeneratedMessage
    implements PAppRequestOrBuilder {
  // Use PAppRequest.newBuilder() to construct.
  private PAppRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
    this.unknownFields = builder.getUnknownFields();
  }
  private PAppRequest(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

  private static final PAppRequest defaultInstance;
  public static PAppRequest getDefaultInstance() {
    return defaultInstance;
  }

  public PAppRequest getDefaultInstanceForType() {
    return defaultInstance;
  }

  private final com.google.protobuf.UnknownFieldSet unknownFields;
  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
    return this.unknownFields;
  }
  private PAppRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    initFields();
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownField(input, unknownFields,
                                   extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            bitField0_ |= 0x00000001;
            authId_ = input.readBytes();
            break;
          }
          case 18: {
            bitField0_ |= 0x00000002;
            sessionId_ = input.readBytes();
            break;
          }
          case 24: {
            bitField0_ |= 0x00000004;
            version_ = input.readInt32();
            break;
          }
          case 34: {
            bitField0_ |= 0x00000008;
            sign_ = input.readBytes();
            break;
          }
          case 42: {
            bitField0_ |= 0x00000010;
            nonce_ = input.readBytes();
            break;
          }
          case 50: {
            if (!((mutable_bitField0_ & 0x00000020) == 0x00000020)) {
              param_ = new java.util.ArrayList<com.argo.sdk.protobuf.PAppRequestParam>();
              mutable_bitField0_ |= 0x00000020;
            }
            param_.add(input.readMessage(com.argo.sdk.protobuf.PAppRequestParam.PARSER, extensionRegistry));
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e.getMessage()).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000020) == 0x00000020)) {
        param_ = java.util.Collections.unmodifiableList(param_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.argo.sdk.protobuf.PAppRequestProto.internal_static_PAppRequest_descriptor;
  }

  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.argo.sdk.protobuf.PAppRequestProto.internal_static_PAppRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.argo.sdk.protobuf.PAppRequest.class, com.argo.sdk.protobuf.PAppRequest.Builder.class);
  }

  public static com.google.protobuf.Parser<PAppRequest> PARSER =
      new com.google.protobuf.AbstractParser<PAppRequest>() {
    public PAppRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new PAppRequest(input, extensionRegistry);
    }
  };

  @java.lang.Override
  public com.google.protobuf.Parser<PAppRequest> getParserForType() {
    return PARSER;
  }

  private int bitField0_;
  // required string authId = 1;
  public static final int AUTHID_FIELD_NUMBER = 1;
  private java.lang.Object authId_;
  /**
   * <code>required string authId = 1;</code>
   */
  public boolean hasAuthId() {
    return ((bitField0_ & 0x00000001) == 0x00000001);
  }
  /**
   * <code>required string authId = 1;</code>
   */
  public java.lang.String getAuthId() {
    java.lang.Object ref = authId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        authId_ = s;
      }
      return s;
    }
  }
  /**
   * <code>required string authId = 1;</code>
   */
  public com.google.protobuf.ByteString
      getAuthIdBytes() {
    java.lang.Object ref = authId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      authId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  // optional string sessionId = 2;
  public static final int SESSIONID_FIELD_NUMBER = 2;
  private java.lang.Object sessionId_;
  /**
   * <code>optional string sessionId = 2;</code>
   */
  public boolean hasSessionId() {
    return ((bitField0_ & 0x00000002) == 0x00000002);
  }
  /**
   * <code>optional string sessionId = 2;</code>
   */
  public java.lang.String getSessionId() {
    java.lang.Object ref = sessionId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        sessionId_ = s;
      }
      return s;
    }
  }
  /**
   * <code>optional string sessionId = 2;</code>
   */
  public com.google.protobuf.ByteString
      getSessionIdBytes() {
    java.lang.Object ref = sessionId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      sessionId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  // optional int32 version = 3;
  public static final int VERSION_FIELD_NUMBER = 3;
  private int version_;
  /**
   * <code>optional int32 version = 3;</code>
   */
  public boolean hasVersion() {
    return ((bitField0_ & 0x00000004) == 0x00000004);
  }
  /**
   * <code>optional int32 version = 3;</code>
   */
  public int getVersion() {
    return version_;
  }

  // optional string sign = 4;
  public static final int SIGN_FIELD_NUMBER = 4;
  private java.lang.Object sign_;
  /**
   * <code>optional string sign = 4;</code>
   */
  public boolean hasSign() {
    return ((bitField0_ & 0x00000008) == 0x00000008);
  }
  /**
   * <code>optional string sign = 4;</code>
   */
  public java.lang.String getSign() {
    java.lang.Object ref = sign_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        sign_ = s;
      }
      return s;
    }
  }
  /**
   * <code>optional string sign = 4;</code>
   */
  public com.google.protobuf.ByteString
      getSignBytes() {
    java.lang.Object ref = sign_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      sign_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  // optional string nonce = 5;
  public static final int NONCE_FIELD_NUMBER = 5;
  private java.lang.Object nonce_;
  /**
   * <code>optional string nonce = 5;</code>
   */
  public boolean hasNonce() {
    return ((bitField0_ & 0x00000010) == 0x00000010);
  }
  /**
   * <code>optional string nonce = 5;</code>
   */
  public java.lang.String getNonce() {
    java.lang.Object ref = nonce_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        nonce_ = s;
      }
      return s;
    }
  }
  /**
   * <code>optional string nonce = 5;</code>
   */
  public com.google.protobuf.ByteString
      getNonceBytes() {
    java.lang.Object ref = nonce_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      nonce_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  // repeated .PAppRequestParam param = 6;
  public static final int PARAM_FIELD_NUMBER = 6;
  private java.util.List<com.argo.sdk.protobuf.PAppRequestParam> param_;
  /**
   * <code>repeated .PAppRequestParam param = 6;</code>
   */
  public java.util.List<com.argo.sdk.protobuf.PAppRequestParam> getParamList() {
    return param_;
  }
  /**
   * <code>repeated .PAppRequestParam param = 6;</code>
   */
  public java.util.List<? extends com.argo.sdk.protobuf.PAppRequestParamOrBuilder> 
      getParamOrBuilderList() {
    return param_;
  }
  /**
   * <code>repeated .PAppRequestParam param = 6;</code>
   */
  public int getParamCount() {
    return param_.size();
  }
  /**
   * <code>repeated .PAppRequestParam param = 6;</code>
   */
  public com.argo.sdk.protobuf.PAppRequestParam getParam(int index) {
    return param_.get(index);
  }
  /**
   * <code>repeated .PAppRequestParam param = 6;</code>
   */
  public com.argo.sdk.protobuf.PAppRequestParamOrBuilder getParamOrBuilder(
      int index) {
    return param_.get(index);
  }

  private void initFields() {
    authId_ = "";
    sessionId_ = "";
    version_ = 0;
    sign_ = "";
    nonce_ = "";
    param_ = java.util.Collections.emptyList();
  }
  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized != -1) return isInitialized == 1;

    if (!hasAuthId()) {
      memoizedIsInitialized = 0;
      return false;
    }
    for (int i = 0; i < getParamCount(); i++) {
      if (!getParam(i).isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
    }
    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    getSerializedSize();
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      output.writeBytes(1, getAuthIdBytes());
    }
    if (((bitField0_ & 0x00000002) == 0x00000002)) {
      output.writeBytes(2, getSessionIdBytes());
    }
    if (((bitField0_ & 0x00000004) == 0x00000004)) {
      output.writeInt32(3, version_);
    }
    if (((bitField0_ & 0x00000008) == 0x00000008)) {
      output.writeBytes(4, getSignBytes());
    }
    if (((bitField0_ & 0x00000010) == 0x00000010)) {
      output.writeBytes(5, getNonceBytes());
    }
    for (int i = 0; i < param_.size(); i++) {
      output.writeMessage(6, param_.get(i));
    }
    getUnknownFields().writeTo(output);
  }

  private int memoizedSerializedSize = -1;
  public int getSerializedSize() {
    int size = memoizedSerializedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(1, getAuthIdBytes());
    }
    if (((bitField0_ & 0x00000002) == 0x00000002)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(2, getSessionIdBytes());
    }
    if (((bitField0_ & 0x00000004) == 0x00000004)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(3, version_);
    }
    if (((bitField0_ & 0x00000008) == 0x00000008)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(4, getSignBytes());
    }
    if (((bitField0_ & 0x00000010) == 0x00000010)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(5, getNonceBytes());
    }
    for (int i = 0; i < param_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(6, param_.get(i));
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSerializedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  protected java.lang.Object writeReplace()
      throws java.io.ObjectStreamException {
    return super.writeReplace();
  }

  public static com.argo.sdk.protobuf.PAppRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.argo.sdk.protobuf.PAppRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.argo.sdk.protobuf.PAppRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.argo.sdk.protobuf.PAppRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.argo.sdk.protobuf.PAppRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static com.argo.sdk.protobuf.PAppRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }
  public static com.argo.sdk.protobuf.PAppRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input);
  }
  public static com.argo.sdk.protobuf.PAppRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input, extensionRegistry);
  }
  public static com.argo.sdk.protobuf.PAppRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static com.argo.sdk.protobuf.PAppRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }

  public static Builder newBuilder() { return Builder.create(); }
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder(com.argo.sdk.protobuf.PAppRequest prototype) {
    return newBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() { return newBuilder(this); }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code PAppRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder>
     implements com.argo.sdk.protobuf.PAppRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.argo.sdk.protobuf.PAppRequestProto.internal_static_PAppRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.argo.sdk.protobuf.PAppRequestProto.internal_static_PAppRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.argo.sdk.protobuf.PAppRequest.class, com.argo.sdk.protobuf.PAppRequest.Builder.class);
    }

    // Construct using com.argo.sdk.protobuf.PAppRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        getParamFieldBuilder();
      }
    }
    private static Builder create() {
      return new Builder();
    }

    public Builder clear() {
      super.clear();
      authId_ = "";
      bitField0_ = (bitField0_ & ~0x00000001);
      sessionId_ = "";
      bitField0_ = (bitField0_ & ~0x00000002);
      version_ = 0;
      bitField0_ = (bitField0_ & ~0x00000004);
      sign_ = "";
      bitField0_ = (bitField0_ & ~0x00000008);
      nonce_ = "";
      bitField0_ = (bitField0_ & ~0x00000010);
      if (paramBuilder_ == null) {
        param_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000020);
      } else {
        paramBuilder_.clear();
      }
      return this;
    }

    public Builder clone() {
      return create().mergeFrom(buildPartial());
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.argo.sdk.protobuf.PAppRequestProto.internal_static_PAppRequest_descriptor;
    }

    public com.argo.sdk.protobuf.PAppRequest getDefaultInstanceForType() {
      return com.argo.sdk.protobuf.PAppRequest.getDefaultInstance();
    }

    public com.argo.sdk.protobuf.PAppRequest build() {
      com.argo.sdk.protobuf.PAppRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.argo.sdk.protobuf.PAppRequest buildPartial() {
      com.argo.sdk.protobuf.PAppRequest result = new com.argo.sdk.protobuf.PAppRequest(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
        to_bitField0_ |= 0x00000001;
      }
      result.authId_ = authId_;
      if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
        to_bitField0_ |= 0x00000002;
      }
      result.sessionId_ = sessionId_;
      if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
        to_bitField0_ |= 0x00000004;
      }
      result.version_ = version_;
      if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
        to_bitField0_ |= 0x00000008;
      }
      result.sign_ = sign_;
      if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
        to_bitField0_ |= 0x00000010;
      }
      result.nonce_ = nonce_;
      if (paramBuilder_ == null) {
        if (((bitField0_ & 0x00000020) == 0x00000020)) {
          param_ = java.util.Collections.unmodifiableList(param_);
          bitField0_ = (bitField0_ & ~0x00000020);
        }
        result.param_ = param_;
      } else {
        result.param_ = paramBuilder_.build();
      }
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.argo.sdk.protobuf.PAppRequest) {
        return mergeFrom((com.argo.sdk.protobuf.PAppRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.argo.sdk.protobuf.PAppRequest other) {
      if (other == com.argo.sdk.protobuf.PAppRequest.getDefaultInstance()) return this;
      if (other.hasAuthId()) {
        bitField0_ |= 0x00000001;
        authId_ = other.authId_;
        onChanged();
      }
      if (other.hasSessionId()) {
        bitField0_ |= 0x00000002;
        sessionId_ = other.sessionId_;
        onChanged();
      }
      if (other.hasVersion()) {
        setVersion(other.getVersion());
      }
      if (other.hasSign()) {
        bitField0_ |= 0x00000008;
        sign_ = other.sign_;
        onChanged();
      }
      if (other.hasNonce()) {
        bitField0_ |= 0x00000010;
        nonce_ = other.nonce_;
        onChanged();
      }
      if (paramBuilder_ == null) {
        if (!other.param_.isEmpty()) {
          if (param_.isEmpty()) {
            param_ = other.param_;
            bitField0_ = (bitField0_ & ~0x00000020);
          } else {
            ensureParamIsMutable();
            param_.addAll(other.param_);
          }
          onChanged();
        }
      } else {
        if (!other.param_.isEmpty()) {
          if (paramBuilder_.isEmpty()) {
            paramBuilder_.dispose();
            paramBuilder_ = null;
            param_ = other.param_;
            bitField0_ = (bitField0_ & ~0x00000020);
            paramBuilder_ = 
              com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                 getParamFieldBuilder() : null;
          } else {
            paramBuilder_.addAllMessages(other.param_);
          }
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      return this;
    }

    public final boolean isInitialized() {
      if (!hasAuthId()) {
        
        return false;
      }
      for (int i = 0; i < getParamCount(); i++) {
        if (!getParam(i).isInitialized()) {
          
          return false;
        }
      }
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.argo.sdk.protobuf.PAppRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.argo.sdk.protobuf.PAppRequest) e.getUnfinishedMessage();
        throw e;
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    // required string authId = 1;
    private java.lang.Object authId_ = "";
    /**
     * <code>required string authId = 1;</code>
     */
    public boolean hasAuthId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string authId = 1;</code>
     */
    public java.lang.String getAuthId() {
      java.lang.Object ref = authId_;
      if (!(ref instanceof java.lang.String)) {
        java.lang.String s = ((com.google.protobuf.ByteString) ref)
            .toStringUtf8();
        authId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>required string authId = 1;</code>
     */
    public com.google.protobuf.ByteString
        getAuthIdBytes() {
      java.lang.Object ref = authId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        authId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>required string authId = 1;</code>
     */
    public Builder setAuthId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
      authId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>required string authId = 1;</code>
     */
    public Builder clearAuthId() {
      bitField0_ = (bitField0_ & ~0x00000001);
      authId_ = getDefaultInstance().getAuthId();
      onChanged();
      return this;
    }
    /**
     * <code>required string authId = 1;</code>
     */
    public Builder setAuthIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
      authId_ = value;
      onChanged();
      return this;
    }

    // optional string sessionId = 2;
    private java.lang.Object sessionId_ = "";
    /**
     * <code>optional string sessionId = 2;</code>
     */
    public boolean hasSessionId() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string sessionId = 2;</code>
     */
    public java.lang.String getSessionId() {
      java.lang.Object ref = sessionId_;
      if (!(ref instanceof java.lang.String)) {
        java.lang.String s = ((com.google.protobuf.ByteString) ref)
            .toStringUtf8();
        sessionId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string sessionId = 2;</code>
     */
    public com.google.protobuf.ByteString
        getSessionIdBytes() {
      java.lang.Object ref = sessionId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sessionId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string sessionId = 2;</code>
     */
    public Builder setSessionId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
      sessionId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string sessionId = 2;</code>
     */
    public Builder clearSessionId() {
      bitField0_ = (bitField0_ & ~0x00000002);
      sessionId_ = getDefaultInstance().getSessionId();
      onChanged();
      return this;
    }
    /**
     * <code>optional string sessionId = 2;</code>
     */
    public Builder setSessionIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
      sessionId_ = value;
      onChanged();
      return this;
    }

    // optional int32 version = 3;
    private int version_ ;
    /**
     * <code>optional int32 version = 3;</code>
     */
    public boolean hasVersion() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional int32 version = 3;</code>
     */
    public int getVersion() {
      return version_;
    }
    /**
     * <code>optional int32 version = 3;</code>
     */
    public Builder setVersion(int value) {
      bitField0_ |= 0x00000004;
      version_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional int32 version = 3;</code>
     */
    public Builder clearVersion() {
      bitField0_ = (bitField0_ & ~0x00000004);
      version_ = 0;
      onChanged();
      return this;
    }

    // optional string sign = 4;
    private java.lang.Object sign_ = "";
    /**
     * <code>optional string sign = 4;</code>
     */
    public boolean hasSign() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional string sign = 4;</code>
     */
    public java.lang.String getSign() {
      java.lang.Object ref = sign_;
      if (!(ref instanceof java.lang.String)) {
        java.lang.String s = ((com.google.protobuf.ByteString) ref)
            .toStringUtf8();
        sign_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string sign = 4;</code>
     */
    public com.google.protobuf.ByteString
        getSignBytes() {
      java.lang.Object ref = sign_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sign_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string sign = 4;</code>
     */
    public Builder setSign(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
      sign_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string sign = 4;</code>
     */
    public Builder clearSign() {
      bitField0_ = (bitField0_ & ~0x00000008);
      sign_ = getDefaultInstance().getSign();
      onChanged();
      return this;
    }
    /**
     * <code>optional string sign = 4;</code>
     */
    public Builder setSignBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
      sign_ = value;
      onChanged();
      return this;
    }

    // optional string nonce = 5;
    private java.lang.Object nonce_ = "";
    /**
     * <code>optional string nonce = 5;</code>
     */
    public boolean hasNonce() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional string nonce = 5;</code>
     */
    public java.lang.String getNonce() {
      java.lang.Object ref = nonce_;
      if (!(ref instanceof java.lang.String)) {
        java.lang.String s = ((com.google.protobuf.ByteString) ref)
            .toStringUtf8();
        nonce_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string nonce = 5;</code>
     */
    public com.google.protobuf.ByteString
        getNonceBytes() {
      java.lang.Object ref = nonce_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        nonce_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string nonce = 5;</code>
     */
    public Builder setNonce(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
      nonce_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string nonce = 5;</code>
     */
    public Builder clearNonce() {
      bitField0_ = (bitField0_ & ~0x00000010);
      nonce_ = getDefaultInstance().getNonce();
      onChanged();
      return this;
    }
    /**
     * <code>optional string nonce = 5;</code>
     */
    public Builder setNonceBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
      nonce_ = value;
      onChanged();
      return this;
    }

    // repeated .PAppRequestParam param = 6;
    private java.util.List<com.argo.sdk.protobuf.PAppRequestParam> param_ =
      java.util.Collections.emptyList();
    private void ensureParamIsMutable() {
      if (!((bitField0_ & 0x00000020) == 0x00000020)) {
        param_ = new java.util.ArrayList<com.argo.sdk.protobuf.PAppRequestParam>(param_);
        bitField0_ |= 0x00000020;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilder<
        com.argo.sdk.protobuf.PAppRequestParam, com.argo.sdk.protobuf.PAppRequestParam.Builder, com.argo.sdk.protobuf.PAppRequestParamOrBuilder> paramBuilder_;

    /**
     * <code>repeated .PAppRequestParam param = 6;</code>
     */
    public java.util.List<com.argo.sdk.protobuf.PAppRequestParam> getParamList() {
      if (paramBuilder_ == null) {
        return java.util.Collections.unmodifiableList(param_);
      } else {
        return paramBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .PAppRequestParam param = 6;</code>
     */
    public int getParamCount() {
      if (paramBuilder_ == null) {
        return param_.size();
      } else {
        return paramBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .PAppRequestParam param = 6;</code>
     */
    public com.argo.sdk.protobuf.PAppRequestParam getParam(int index) {
      if (paramBuilder_ == null) {
        return param_.get(index);
      } else {
        return paramBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .PAppRequestParam param = 6;</code>
     */
    public Builder setParam(
        int index, com.argo.sdk.protobuf.PAppRequestParam value) {
      if (paramBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureParamIsMutable();
        param_.set(index, value);
        onChanged();
      } else {
        paramBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .PAppRequestParam param = 6;</code>
     */
    public Builder setParam(
        int index, com.argo.sdk.protobuf.PAppRequestParam.Builder builderForValue) {
      if (paramBuilder_ == null) {
        ensureParamIsMutable();
        param_.set(index, builderForValue.build());
        onChanged();
      } else {
        paramBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .PAppRequestParam param = 6;</code>
     */
    public Builder addParam(com.argo.sdk.protobuf.PAppRequestParam value) {
      if (paramBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureParamIsMutable();
        param_.add(value);
        onChanged();
      } else {
        paramBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .PAppRequestParam param = 6;</code>
     */
    public Builder addParam(
        int index, com.argo.sdk.protobuf.PAppRequestParam value) {
      if (paramBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureParamIsMutable();
        param_.add(index, value);
        onChanged();
      } else {
        paramBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .PAppRequestParam param = 6;</code>
     */
    public Builder addParam(
        com.argo.sdk.protobuf.PAppRequestParam.Builder builderForValue) {
      if (paramBuilder_ == null) {
        ensureParamIsMutable();
        param_.add(builderForValue.build());
        onChanged();
      } else {
        paramBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .PAppRequestParam param = 6;</code>
     */
    public Builder addParam(
        int index, com.argo.sdk.protobuf.PAppRequestParam.Builder builderForValue) {
      if (paramBuilder_ == null) {
        ensureParamIsMutable();
        param_.add(index, builderForValue.build());
        onChanged();
      } else {
        paramBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .PAppRequestParam param = 6;</code>
     */
    public Builder addAllParam(
        java.lang.Iterable<? extends com.argo.sdk.protobuf.PAppRequestParam> values) {
      if (paramBuilder_ == null) {
        ensureParamIsMutable();
        super.addAll(values, param_);
        onChanged();
      } else {
        paramBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .PAppRequestParam param = 6;</code>
     */
    public Builder clearParam() {
      if (paramBuilder_ == null) {
        param_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000020);
        onChanged();
      } else {
        paramBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .PAppRequestParam param = 6;</code>
     */
    public Builder removeParam(int index) {
      if (paramBuilder_ == null) {
        ensureParamIsMutable();
        param_.remove(index);
        onChanged();
      } else {
        paramBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .PAppRequestParam param = 6;</code>
     */
    public com.argo.sdk.protobuf.PAppRequestParam.Builder getParamBuilder(
        int index) {
      return getParamFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .PAppRequestParam param = 6;</code>
     */
    public com.argo.sdk.protobuf.PAppRequestParamOrBuilder getParamOrBuilder(
        int index) {
      if (paramBuilder_ == null) {
        return param_.get(index);  } else {
        return paramBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .PAppRequestParam param = 6;</code>
     */
    public java.util.List<? extends com.argo.sdk.protobuf.PAppRequestParamOrBuilder> 
         getParamOrBuilderList() {
      if (paramBuilder_ != null) {
        return paramBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(param_);
      }
    }
    /**
     * <code>repeated .PAppRequestParam param = 6;</code>
     */
    public com.argo.sdk.protobuf.PAppRequestParam.Builder addParamBuilder() {
      return getParamFieldBuilder().addBuilder(
          com.argo.sdk.protobuf.PAppRequestParam.getDefaultInstance());
    }
    /**
     * <code>repeated .PAppRequestParam param = 6;</code>
     */
    public com.argo.sdk.protobuf.PAppRequestParam.Builder addParamBuilder(
        int index) {
      return getParamFieldBuilder().addBuilder(
          index, com.argo.sdk.protobuf.PAppRequestParam.getDefaultInstance());
    }
    /**
     * <code>repeated .PAppRequestParam param = 6;</code>
     */
    public java.util.List<com.argo.sdk.protobuf.PAppRequestParam.Builder> 
         getParamBuilderList() {
      return getParamFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilder<
        com.argo.sdk.protobuf.PAppRequestParam, com.argo.sdk.protobuf.PAppRequestParam.Builder, com.argo.sdk.protobuf.PAppRequestParamOrBuilder> 
        getParamFieldBuilder() {
      if (paramBuilder_ == null) {
        paramBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
            com.argo.sdk.protobuf.PAppRequestParam, com.argo.sdk.protobuf.PAppRequestParam.Builder, com.argo.sdk.protobuf.PAppRequestParamOrBuilder>(
                param_,
                ((bitField0_ & 0x00000020) == 0x00000020),
                getParentForChildren(),
                isClean());
        param_ = null;
      }
      return paramBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:PAppRequest)
  }

  static {
    defaultInstance = new PAppRequest(true);
    defaultInstance.initFields();
  }

  // @@protoc_insertion_point(class_scope:PAppRequest)
}

