// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mobile_proto.proto

package com.argo.core.protobuf;

public interface ProtobufMessageOrBuilder
    extends com.google.protobuf.MessageOrBuilder {

  // optional string msg = 1;
  /**
   * <code>optional string msg = 1;</code>
   */
  boolean hasMsg();
  /**
   * <code>optional string msg = 1;</code>
   */
  java.lang.String getMsg();
  /**
   * <code>optional string msg = 1;</code>
   */
  com.google.protobuf.ByteString
      getMsgBytes();

  // optional string sessionId = 2;
  /**
   * <code>optional string sessionId = 2;</code>
   */
  boolean hasSessionId();
  /**
   * <code>optional string sessionId = 2;</code>
   */
  java.lang.String getSessionId();
  /**
   * <code>optional string sessionId = 2;</code>
   */
  com.google.protobuf.ByteString
      getSessionIdBytes();

  // optional string version = 3;
  /**
   * <code>optional string version = 3;</code>
   */
  boolean hasVersion();
  /**
   * <code>optional string version = 3;</code>
   */
  java.lang.String getVersion();
  /**
   * <code>optional string version = 3;</code>
   */
  com.google.protobuf.ByteString
      getVersionBytes();

  // required int32 code = 4;
  /**
   * <code>required int32 code = 4;</code>
   */
  boolean hasCode();
  /**
   * <code>required int32 code = 4;</code>
   */
  int getCode();

  // required int32 total = 5;
  /**
   * <code>required int32 total = 5;</code>
   */
  boolean hasTotal();
  /**
   * <code>required int32 total = 5;</code>
   */
  int getTotal();

  // repeated bytes data = 6;
  /**
   * <code>repeated bytes data = 6;</code>
   */
  java.util.List<com.google.protobuf.ByteString> getDataList();
  /**
   * <code>repeated bytes data = 6;</code>
   */
  int getDataCount();
  /**
   * <code>repeated bytes data = 6;</code>
   */
  com.google.protobuf.ByteString getData(int index);

  // repeated string errors = 7;
  /**
   * <code>repeated string errors = 7;</code>
   */
  java.util.List<java.lang.String>
  getErrorsList();
  /**
   * <code>repeated string errors = 7;</code>
   */
  int getErrorsCount();
  /**
   * <code>repeated string errors = 7;</code>
   */
  java.lang.String getErrors(int index);
  /**
   * <code>repeated string errors = 7;</code>
   */
  com.google.protobuf.ByteString
      getErrorsBytes(int index);
}
