// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: app_session.proto

package android.com.inno.sdk.protobuf;

public final class PAppSessionProto {
  private PAppSessionProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  static com.google.protobuf.Descriptors.Descriptor
    internal_static_PAppSession_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_PAppSession_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021app_session.proto\"\345\003\n\013PAppSession\022\021\n\ts" +
      "essionId\030\001 \001(\t\022\020\n\010realName\030\002 \001(\t\022\020\n\010user" +
      "Name\030\003 \001(\t\022\016\n\006userId\030\004 \001(\003\022\016\n\006secret\030\005 \001" +
      "(\t\022\022\n\nsigninDate\030\006 \001(\t\022\027\n\017profileImageUr" +
      "l\030\007 \001(\t\022\017\n\007appName\030\010 \001(\t\022\022\n\ndeviceName\030\t" +
      " \001(\t\022\030\n\020deviceScreenSize\030\n \001(\t\022\016\n\006osName" +
      "\030\013 \001(\t\022\021\n\tosVersion\030\014 \001(\t\022\026\n\016packageVers" +
      "ion\030\r \001(\t\022\023\n\013packageName\030\016 \001(\t\022\020\n\010device" +
      "Id\030\017 \001(\t\022\023\n\013deviceToken\030\020 \001(\t\022\023\n\013apnsEna" +
      "bled\030\021 \001(\005\022\024\n\014latesAppVers\030\022 \001(\t\022\030\n\020loca",
      "leIdentifier\030\023 \001(\t\022\020\n\010latitude\030\024 \001(\002\022\021\n\t" +
      "longitude\030\025 \001(\002\022\016\n\006cityId\030\026 \001(\005\022\020\n\010userK" +
      "ind\030\027 \001(\005\022\020\n\010userDemo\030\030 \001(\005B3\n\035android.c" +
      "om.inno.sdk.protobufB\020PAppSessionProtoP\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_PAppSession_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_PAppSession_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_PAppSession_descriptor,
              new java.lang.String[] { "SessionId", "RealName", "UserName", "UserId", "Secret", "SigninDate", "ProfileImageUrl", "AppName", "DeviceName", "DeviceScreenSize", "OsName", "OsVersion", "PackageVersion", "PackageName", "DeviceId", "DeviceToken", "ApnsEnabled", "LatesAppVers", "LocaleIdentifier", "Latitude", "Longitude", "CityId", "UserKind", "UserDemo", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
