// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: app_session.proto

package android.com.inno.sdk.protobuf;

/**
 * Protobuf type {@code PAppSession}
 */
public  final class PAppSession extends
    com.google.protobuf.GeneratedMessage
    implements PAppSessionOrBuilder {
  // Use PAppSession.newBuilder() to construct.
  private PAppSession(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
    this.unknownFields = builder.getUnknownFields();
  }
  private PAppSession(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

  private static final PAppSession defaultInstance;
  public static PAppSession getDefaultInstance() {
    return defaultInstance;
  }

  public PAppSession getDefaultInstanceForType() {
    return defaultInstance;
  }

  private final com.google.protobuf.UnknownFieldSet unknownFields;
  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
    return this.unknownFields;
  }
  private PAppSession(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    initFields();
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownField(input, unknownFields,
                                   extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            bitField0_ |= 0x00000001;
            sessionId_ = input.readBytes();
            break;
          }
          case 18: {
            bitField0_ |= 0x00000002;
            realName_ = input.readBytes();
            break;
          }
          case 26: {
            bitField0_ |= 0x00000004;
            userName_ = input.readBytes();
            break;
          }
          case 32: {
            bitField0_ |= 0x00000008;
            userId_ = input.readInt64();
            break;
          }
          case 42: {
            bitField0_ |= 0x00000010;
            secret_ = input.readBytes();
            break;
          }
          case 50: {
            bitField0_ |= 0x00000020;
            signinDate_ = input.readBytes();
            break;
          }
          case 58: {
            bitField0_ |= 0x00000040;
            profileImageUrl_ = input.readBytes();
            break;
          }
          case 66: {
            bitField0_ |= 0x00000080;
            appName_ = input.readBytes();
            break;
          }
          case 74: {
            bitField0_ |= 0x00000100;
            deviceName_ = input.readBytes();
            break;
          }
          case 82: {
            bitField0_ |= 0x00000200;
            deviceScreenSize_ = input.readBytes();
            break;
          }
          case 90: {
            bitField0_ |= 0x00000400;
            osName_ = input.readBytes();
            break;
          }
          case 98: {
            bitField0_ |= 0x00000800;
            osVersion_ = input.readBytes();
            break;
          }
          case 106: {
            bitField0_ |= 0x00001000;
            packageVersion_ = input.readBytes();
            break;
          }
          case 114: {
            bitField0_ |= 0x00002000;
            packageName_ = input.readBytes();
            break;
          }
          case 122: {
            bitField0_ |= 0x00004000;
            deviceId_ = input.readBytes();
            break;
          }
          case 130: {
            bitField0_ |= 0x00008000;
            deviceToken_ = input.readBytes();
            break;
          }
          case 136: {
            bitField0_ |= 0x00010000;
            apnsEnabled_ = input.readInt32();
            break;
          }
          case 146: {
            bitField0_ |= 0x00020000;
            latesAppVers_ = input.readBytes();
            break;
          }
          case 154: {
            bitField0_ |= 0x00040000;
            localeIdentifier_ = input.readBytes();
            break;
          }
          case 165: {
            bitField0_ |= 0x00080000;
            latitude_ = input.readFloat();
            break;
          }
          case 173: {
            bitField0_ |= 0x00100000;
            longitude_ = input.readFloat();
            break;
          }
          case 176: {
            bitField0_ |= 0x00200000;
            cityId_ = input.readInt32();
            break;
          }
          case 184: {
            bitField0_ |= 0x00400000;
            userKind_ = input.readInt32();
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e.getMessage()).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return android.com.inno.sdk.protobuf.PAppSessionProto.internal_static_PAppSession_descriptor;
  }

  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return android.com.inno.sdk.protobuf.PAppSessionProto.internal_static_PAppSession_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            android.com.inno.sdk.protobuf.PAppSession.class, android.com.inno.sdk.protobuf.PAppSession.Builder.class);
  }

  public static com.google.protobuf.Parser<PAppSession> PARSER =
      new com.google.protobuf.AbstractParser<PAppSession>() {
    public PAppSession parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new PAppSession(input, extensionRegistry);
    }
  };

  @java.lang.Override
  public com.google.protobuf.Parser<PAppSession> getParserForType() {
    return PARSER;
  }

  private int bitField0_;
  // optional string sessionId = 1;
  public static final int SESSIONID_FIELD_NUMBER = 1;
  private java.lang.Object sessionId_;
  /**
   * <code>optional string sessionId = 1;</code>
   */
  public boolean hasSessionId() {
    return ((bitField0_ & 0x00000001) == 0x00000001);
  }
  /**
   * <code>optional string sessionId = 1;</code>
   */
  public java.lang.String getSessionId() {
    java.lang.Object ref = sessionId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        sessionId_ = s;
      }
      return s;
    }
  }
  /**
   * <code>optional string sessionId = 1;</code>
   */
  public com.google.protobuf.ByteString
      getSessionIdBytes() {
    java.lang.Object ref = sessionId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      sessionId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  // optional string realName = 2;
  public static final int REALNAME_FIELD_NUMBER = 2;
  private java.lang.Object realName_;
  /**
   * <code>optional string realName = 2;</code>
   */
  public boolean hasRealName() {
    return ((bitField0_ & 0x00000002) == 0x00000002);
  }
  /**
   * <code>optional string realName = 2;</code>
   */
  public java.lang.String getRealName() {
    java.lang.Object ref = realName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        realName_ = s;
      }
      return s;
    }
  }
  /**
   * <code>optional string realName = 2;</code>
   */
  public com.google.protobuf.ByteString
      getRealNameBytes() {
    java.lang.Object ref = realName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      realName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  // optional string userName = 3;
  public static final int USERNAME_FIELD_NUMBER = 3;
  private java.lang.Object userName_;
  /**
   * <code>optional string userName = 3;</code>
   */
  public boolean hasUserName() {
    return ((bitField0_ & 0x00000004) == 0x00000004);
  }
  /**
   * <code>optional string userName = 3;</code>
   */
  public java.lang.String getUserName() {
    java.lang.Object ref = userName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        userName_ = s;
      }
      return s;
    }
  }
  /**
   * <code>optional string userName = 3;</code>
   */
  public com.google.protobuf.ByteString
      getUserNameBytes() {
    java.lang.Object ref = userName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      userName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  // optional int64 userId = 4;
  public static final int USERID_FIELD_NUMBER = 4;
  private long userId_;
  /**
   * <code>optional int64 userId = 4;</code>
   */
  public boolean hasUserId() {
    return ((bitField0_ & 0x00000008) == 0x00000008);
  }
  /**
   * <code>optional int64 userId = 4;</code>
   */
  public long getUserId() {
    return userId_;
  }

  // optional string secret = 5;
  public static final int SECRET_FIELD_NUMBER = 5;
  private java.lang.Object secret_;
  /**
   * <code>optional string secret = 5;</code>
   */
  public boolean hasSecret() {
    return ((bitField0_ & 0x00000010) == 0x00000010);
  }
  /**
   * <code>optional string secret = 5;</code>
   */
  public java.lang.String getSecret() {
    java.lang.Object ref = secret_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        secret_ = s;
      }
      return s;
    }
  }
  /**
   * <code>optional string secret = 5;</code>
   */
  public com.google.protobuf.ByteString
      getSecretBytes() {
    java.lang.Object ref = secret_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      secret_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  // optional string signinDate = 6;
  public static final int SIGNINDATE_FIELD_NUMBER = 6;
  private java.lang.Object signinDate_;
  /**
   * <code>optional string signinDate = 6;</code>
   */
  public boolean hasSigninDate() {
    return ((bitField0_ & 0x00000020) == 0x00000020);
  }
  /**
   * <code>optional string signinDate = 6;</code>
   */
  public java.lang.String getSigninDate() {
    java.lang.Object ref = signinDate_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        signinDate_ = s;
      }
      return s;
    }
  }
  /**
   * <code>optional string signinDate = 6;</code>
   */
  public com.google.protobuf.ByteString
      getSigninDateBytes() {
    java.lang.Object ref = signinDate_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      signinDate_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  // optional string profileImageUrl = 7;
  public static final int PROFILEIMAGEURL_FIELD_NUMBER = 7;
  private java.lang.Object profileImageUrl_;
  /**
   * <code>optional string profileImageUrl = 7;</code>
   */
  public boolean hasProfileImageUrl() {
    return ((bitField0_ & 0x00000040) == 0x00000040);
  }
  /**
   * <code>optional string profileImageUrl = 7;</code>
   */
  public java.lang.String getProfileImageUrl() {
    java.lang.Object ref = profileImageUrl_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        profileImageUrl_ = s;
      }
      return s;
    }
  }
  /**
   * <code>optional string profileImageUrl = 7;</code>
   */
  public com.google.protobuf.ByteString
      getProfileImageUrlBytes() {
    java.lang.Object ref = profileImageUrl_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      profileImageUrl_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  // optional string appName = 8;
  public static final int APPNAME_FIELD_NUMBER = 8;
  private java.lang.Object appName_;
  /**
   * <code>optional string appName = 8;</code>
   */
  public boolean hasAppName() {
    return ((bitField0_ & 0x00000080) == 0x00000080);
  }
  /**
   * <code>optional string appName = 8;</code>
   */
  public java.lang.String getAppName() {
    java.lang.Object ref = appName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        appName_ = s;
      }
      return s;
    }
  }
  /**
   * <code>optional string appName = 8;</code>
   */
  public com.google.protobuf.ByteString
      getAppNameBytes() {
    java.lang.Object ref = appName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      appName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  // optional string deviceName = 9;
  public static final int DEVICENAME_FIELD_NUMBER = 9;
  private java.lang.Object deviceName_;
  /**
   * <code>optional string deviceName = 9;</code>
   */
  public boolean hasDeviceName() {
    return ((bitField0_ & 0x00000100) == 0x00000100);
  }
  /**
   * <code>optional string deviceName = 9;</code>
   */
  public java.lang.String getDeviceName() {
    java.lang.Object ref = deviceName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        deviceName_ = s;
      }
      return s;
    }
  }
  /**
   * <code>optional string deviceName = 9;</code>
   */
  public com.google.protobuf.ByteString
      getDeviceNameBytes() {
    java.lang.Object ref = deviceName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      deviceName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  // optional string deviceScreenSize = 10;
  public static final int DEVICESCREENSIZE_FIELD_NUMBER = 10;
  private java.lang.Object deviceScreenSize_;
  /**
   * <code>optional string deviceScreenSize = 10;</code>
   */
  public boolean hasDeviceScreenSize() {
    return ((bitField0_ & 0x00000200) == 0x00000200);
  }
  /**
   * <code>optional string deviceScreenSize = 10;</code>
   */
  public java.lang.String getDeviceScreenSize() {
    java.lang.Object ref = deviceScreenSize_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        deviceScreenSize_ = s;
      }
      return s;
    }
  }
  /**
   * <code>optional string deviceScreenSize = 10;</code>
   */
  public com.google.protobuf.ByteString
      getDeviceScreenSizeBytes() {
    java.lang.Object ref = deviceScreenSize_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      deviceScreenSize_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  // optional string osName = 11;
  public static final int OSNAME_FIELD_NUMBER = 11;
  private java.lang.Object osName_;
  /**
   * <code>optional string osName = 11;</code>
   */
  public boolean hasOsName() {
    return ((bitField0_ & 0x00000400) == 0x00000400);
  }
  /**
   * <code>optional string osName = 11;</code>
   */
  public java.lang.String getOsName() {
    java.lang.Object ref = osName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        osName_ = s;
      }
      return s;
    }
  }
  /**
   * <code>optional string osName = 11;</code>
   */
  public com.google.protobuf.ByteString
      getOsNameBytes() {
    java.lang.Object ref = osName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      osName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  // optional string osVersion = 12;
  public static final int OSVERSION_FIELD_NUMBER = 12;
  private java.lang.Object osVersion_;
  /**
   * <code>optional string osVersion = 12;</code>
   */
  public boolean hasOsVersion() {
    return ((bitField0_ & 0x00000800) == 0x00000800);
  }
  /**
   * <code>optional string osVersion = 12;</code>
   */
  public java.lang.String getOsVersion() {
    java.lang.Object ref = osVersion_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        osVersion_ = s;
      }
      return s;
    }
  }
  /**
   * <code>optional string osVersion = 12;</code>
   */
  public com.google.protobuf.ByteString
      getOsVersionBytes() {
    java.lang.Object ref = osVersion_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      osVersion_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  // optional string packageVersion = 13;
  public static final int PACKAGEVERSION_FIELD_NUMBER = 13;
  private java.lang.Object packageVersion_;
  /**
   * <code>optional string packageVersion = 13;</code>
   */
  public boolean hasPackageVersion() {
    return ((bitField0_ & 0x00001000) == 0x00001000);
  }
  /**
   * <code>optional string packageVersion = 13;</code>
   */
  public java.lang.String getPackageVersion() {
    java.lang.Object ref = packageVersion_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        packageVersion_ = s;
      }
      return s;
    }
  }
  /**
   * <code>optional string packageVersion = 13;</code>
   */
  public com.google.protobuf.ByteString
      getPackageVersionBytes() {
    java.lang.Object ref = packageVersion_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      packageVersion_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  // optional string packageName = 14;
  public static final int PACKAGENAME_FIELD_NUMBER = 14;
  private java.lang.Object packageName_;
  /**
   * <code>optional string packageName = 14;</code>
   */
  public boolean hasPackageName() {
    return ((bitField0_ & 0x00002000) == 0x00002000);
  }
  /**
   * <code>optional string packageName = 14;</code>
   */
  public java.lang.String getPackageName() {
    java.lang.Object ref = packageName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        packageName_ = s;
      }
      return s;
    }
  }
  /**
   * <code>optional string packageName = 14;</code>
   */
  public com.google.protobuf.ByteString
      getPackageNameBytes() {
    java.lang.Object ref = packageName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      packageName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  // optional string deviceId = 15;
  public static final int DEVICEID_FIELD_NUMBER = 15;
  private java.lang.Object deviceId_;
  /**
   * <code>optional string deviceId = 15;</code>
   */
  public boolean hasDeviceId() {
    return ((bitField0_ & 0x00004000) == 0x00004000);
  }
  /**
   * <code>optional string deviceId = 15;</code>
   */
  public java.lang.String getDeviceId() {
    java.lang.Object ref = deviceId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        deviceId_ = s;
      }
      return s;
    }
  }
  /**
   * <code>optional string deviceId = 15;</code>
   */
  public com.google.protobuf.ByteString
      getDeviceIdBytes() {
    java.lang.Object ref = deviceId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      deviceId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  // optional string deviceToken = 16;
  public static final int DEVICETOKEN_FIELD_NUMBER = 16;
  private java.lang.Object deviceToken_;
  /**
   * <code>optional string deviceToken = 16;</code>
   */
  public boolean hasDeviceToken() {
    return ((bitField0_ & 0x00008000) == 0x00008000);
  }
  /**
   * <code>optional string deviceToken = 16;</code>
   */
  public java.lang.String getDeviceToken() {
    java.lang.Object ref = deviceToken_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        deviceToken_ = s;
      }
      return s;
    }
  }
  /**
   * <code>optional string deviceToken = 16;</code>
   */
  public com.google.protobuf.ByteString
      getDeviceTokenBytes() {
    java.lang.Object ref = deviceToken_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      deviceToken_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  // optional int32 apnsEnabled = 17;
  public static final int APNSENABLED_FIELD_NUMBER = 17;
  private int apnsEnabled_;
  /**
   * <code>optional int32 apnsEnabled = 17;</code>
   */
  public boolean hasApnsEnabled() {
    return ((bitField0_ & 0x00010000) == 0x00010000);
  }
  /**
   * <code>optional int32 apnsEnabled = 17;</code>
   */
  public int getApnsEnabled() {
    return apnsEnabled_;
  }

  // optional string latesAppVers = 18;
  public static final int LATESAPPVERS_FIELD_NUMBER = 18;
  private java.lang.Object latesAppVers_;
  /**
   * <code>optional string latesAppVers = 18;</code>
   */
  public boolean hasLatesAppVers() {
    return ((bitField0_ & 0x00020000) == 0x00020000);
  }
  /**
   * <code>optional string latesAppVers = 18;</code>
   */
  public java.lang.String getLatesAppVers() {
    java.lang.Object ref = latesAppVers_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        latesAppVers_ = s;
      }
      return s;
    }
  }
  /**
   * <code>optional string latesAppVers = 18;</code>
   */
  public com.google.protobuf.ByteString
      getLatesAppVersBytes() {
    java.lang.Object ref = latesAppVers_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      latesAppVers_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  // optional string localeIdentifier = 19;
  public static final int LOCALEIDENTIFIER_FIELD_NUMBER = 19;
  private java.lang.Object localeIdentifier_;
  /**
   * <code>optional string localeIdentifier = 19;</code>
   */
  public boolean hasLocaleIdentifier() {
    return ((bitField0_ & 0x00040000) == 0x00040000);
  }
  /**
   * <code>optional string localeIdentifier = 19;</code>
   */
  public java.lang.String getLocaleIdentifier() {
    java.lang.Object ref = localeIdentifier_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        localeIdentifier_ = s;
      }
      return s;
    }
  }
  /**
   * <code>optional string localeIdentifier = 19;</code>
   */
  public com.google.protobuf.ByteString
      getLocaleIdentifierBytes() {
    java.lang.Object ref = localeIdentifier_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      localeIdentifier_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  // optional float latitude = 20;
  public static final int LATITUDE_FIELD_NUMBER = 20;
  private float latitude_;
  /**
   * <code>optional float latitude = 20;</code>
   */
  public boolean hasLatitude() {
    return ((bitField0_ & 0x00080000) == 0x00080000);
  }
  /**
   * <code>optional float latitude = 20;</code>
   */
  public float getLatitude() {
    return latitude_;
  }

  // optional float longitude = 21;
  public static final int LONGITUDE_FIELD_NUMBER = 21;
  private float longitude_;
  /**
   * <code>optional float longitude = 21;</code>
   */
  public boolean hasLongitude() {
    return ((bitField0_ & 0x00100000) == 0x00100000);
  }
  /**
   * <code>optional float longitude = 21;</code>
   */
  public float getLongitude() {
    return longitude_;
  }

  // optional int32 cityId = 22;
  public static final int CITYID_FIELD_NUMBER = 22;
  private int cityId_;
  /**
   * <code>optional int32 cityId = 22;</code>
   */
  public boolean hasCityId() {
    return ((bitField0_ & 0x00200000) == 0x00200000);
  }
  /**
   * <code>optional int32 cityId = 22;</code>
   */
  public int getCityId() {
    return cityId_;
  }

  // optional int32 userKind = 23;
  public static final int USERKIND_FIELD_NUMBER = 23;
  private int userKind_;
  /**
   * <code>optional int32 userKind = 23;</code>
   */
  public boolean hasUserKind() {
    return ((bitField0_ & 0x00400000) == 0x00400000);
  }
  /**
   * <code>optional int32 userKind = 23;</code>
   */
  public int getUserKind() {
    return userKind_;
  }

  private void initFields() {
    sessionId_ = "";
    realName_ = "";
    userName_ = "";
    userId_ = 0L;
    secret_ = "";
    signinDate_ = "";
    profileImageUrl_ = "";
    appName_ = "";
    deviceName_ = "";
    deviceScreenSize_ = "";
    osName_ = "";
    osVersion_ = "";
    packageVersion_ = "";
    packageName_ = "";
    deviceId_ = "";
    deviceToken_ = "";
    apnsEnabled_ = 0;
    latesAppVers_ = "";
    localeIdentifier_ = "";
    latitude_ = 0F;
    longitude_ = 0F;
    cityId_ = 0;
    userKind_ = 0;
  }
  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized != -1) return isInitialized == 1;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    getSerializedSize();
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      output.writeBytes(1, getSessionIdBytes());
    }
    if (((bitField0_ & 0x00000002) == 0x00000002)) {
      output.writeBytes(2, getRealNameBytes());
    }
    if (((bitField0_ & 0x00000004) == 0x00000004)) {
      output.writeBytes(3, getUserNameBytes());
    }
    if (((bitField0_ & 0x00000008) == 0x00000008)) {
      output.writeInt64(4, userId_);
    }
    if (((bitField0_ & 0x00000010) == 0x00000010)) {
      output.writeBytes(5, getSecretBytes());
    }
    if (((bitField0_ & 0x00000020) == 0x00000020)) {
      output.writeBytes(6, getSigninDateBytes());
    }
    if (((bitField0_ & 0x00000040) == 0x00000040)) {
      output.writeBytes(7, getProfileImageUrlBytes());
    }
    if (((bitField0_ & 0x00000080) == 0x00000080)) {
      output.writeBytes(8, getAppNameBytes());
    }
    if (((bitField0_ & 0x00000100) == 0x00000100)) {
      output.writeBytes(9, getDeviceNameBytes());
    }
    if (((bitField0_ & 0x00000200) == 0x00000200)) {
      output.writeBytes(10, getDeviceScreenSizeBytes());
    }
    if (((bitField0_ & 0x00000400) == 0x00000400)) {
      output.writeBytes(11, getOsNameBytes());
    }
    if (((bitField0_ & 0x00000800) == 0x00000800)) {
      output.writeBytes(12, getOsVersionBytes());
    }
    if (((bitField0_ & 0x00001000) == 0x00001000)) {
      output.writeBytes(13, getPackageVersionBytes());
    }
    if (((bitField0_ & 0x00002000) == 0x00002000)) {
      output.writeBytes(14, getPackageNameBytes());
    }
    if (((bitField0_ & 0x00004000) == 0x00004000)) {
      output.writeBytes(15, getDeviceIdBytes());
    }
    if (((bitField0_ & 0x00008000) == 0x00008000)) {
      output.writeBytes(16, getDeviceTokenBytes());
    }
    if (((bitField0_ & 0x00010000) == 0x00010000)) {
      output.writeInt32(17, apnsEnabled_);
    }
    if (((bitField0_ & 0x00020000) == 0x00020000)) {
      output.writeBytes(18, getLatesAppVersBytes());
    }
    if (((bitField0_ & 0x00040000) == 0x00040000)) {
      output.writeBytes(19, getLocaleIdentifierBytes());
    }
    if (((bitField0_ & 0x00080000) == 0x00080000)) {
      output.writeFloat(20, latitude_);
    }
    if (((bitField0_ & 0x00100000) == 0x00100000)) {
      output.writeFloat(21, longitude_);
    }
    if (((bitField0_ & 0x00200000) == 0x00200000)) {
      output.writeInt32(22, cityId_);
    }
    if (((bitField0_ & 0x00400000) == 0x00400000)) {
      output.writeInt32(23, userKind_);
    }
    getUnknownFields().writeTo(output);
  }

  private int memoizedSerializedSize = -1;
  public int getSerializedSize() {
    int size = memoizedSerializedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(1, getSessionIdBytes());
    }
    if (((bitField0_ & 0x00000002) == 0x00000002)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(2, getRealNameBytes());
    }
    if (((bitField0_ & 0x00000004) == 0x00000004)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(3, getUserNameBytes());
    }
    if (((bitField0_ & 0x00000008) == 0x00000008)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(4, userId_);
    }
    if (((bitField0_ & 0x00000010) == 0x00000010)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(5, getSecretBytes());
    }
    if (((bitField0_ & 0x00000020) == 0x00000020)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(6, getSigninDateBytes());
    }
    if (((bitField0_ & 0x00000040) == 0x00000040)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(7, getProfileImageUrlBytes());
    }
    if (((bitField0_ & 0x00000080) == 0x00000080)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(8, getAppNameBytes());
    }
    if (((bitField0_ & 0x00000100) == 0x00000100)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(9, getDeviceNameBytes());
    }
    if (((bitField0_ & 0x00000200) == 0x00000200)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(10, getDeviceScreenSizeBytes());
    }
    if (((bitField0_ & 0x00000400) == 0x00000400)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(11, getOsNameBytes());
    }
    if (((bitField0_ & 0x00000800) == 0x00000800)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(12, getOsVersionBytes());
    }
    if (((bitField0_ & 0x00001000) == 0x00001000)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(13, getPackageVersionBytes());
    }
    if (((bitField0_ & 0x00002000) == 0x00002000)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(14, getPackageNameBytes());
    }
    if (((bitField0_ & 0x00004000) == 0x00004000)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(15, getDeviceIdBytes());
    }
    if (((bitField0_ & 0x00008000) == 0x00008000)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(16, getDeviceTokenBytes());
    }
    if (((bitField0_ & 0x00010000) == 0x00010000)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(17, apnsEnabled_);
    }
    if (((bitField0_ & 0x00020000) == 0x00020000)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(18, getLatesAppVersBytes());
    }
    if (((bitField0_ & 0x00040000) == 0x00040000)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(19, getLocaleIdentifierBytes());
    }
    if (((bitField0_ & 0x00080000) == 0x00080000)) {
      size += com.google.protobuf.CodedOutputStream
        .computeFloatSize(20, latitude_);
    }
    if (((bitField0_ & 0x00100000) == 0x00100000)) {
      size += com.google.protobuf.CodedOutputStream
        .computeFloatSize(21, longitude_);
    }
    if (((bitField0_ & 0x00200000) == 0x00200000)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(22, cityId_);
    }
    if (((bitField0_ & 0x00400000) == 0x00400000)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(23, userKind_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSerializedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  protected java.lang.Object writeReplace()
      throws java.io.ObjectStreamException {
    return super.writeReplace();
  }

  public static android.com.inno.sdk.protobuf.PAppSession parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static android.com.inno.sdk.protobuf.PAppSession parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static android.com.inno.sdk.protobuf.PAppSession parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static android.com.inno.sdk.protobuf.PAppSession parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static android.com.inno.sdk.protobuf.PAppSession parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static android.com.inno.sdk.protobuf.PAppSession parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }
  public static android.com.inno.sdk.protobuf.PAppSession parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input);
  }
  public static android.com.inno.sdk.protobuf.PAppSession parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input, extensionRegistry);
  }
  public static android.com.inno.sdk.protobuf.PAppSession parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static android.com.inno.sdk.protobuf.PAppSession parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }

  public static Builder newBuilder() { return Builder.create(); }
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder(android.com.inno.sdk.protobuf.PAppSession prototype) {
    return newBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() { return newBuilder(this); }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code PAppSession}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder>
     implements android.com.inno.sdk.protobuf.PAppSessionOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return android.com.inno.sdk.protobuf.PAppSessionProto.internal_static_PAppSession_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return android.com.inno.sdk.protobuf.PAppSessionProto.internal_static_PAppSession_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              android.com.inno.sdk.protobuf.PAppSession.class, android.com.inno.sdk.protobuf.PAppSession.Builder.class);
    }

    // Construct using android.com.inno.sdk.protobuf.PAppSession.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
      }
    }
    private static Builder create() {
      return new Builder();
    }

    public Builder clear() {
      super.clear();
      sessionId_ = "";
      bitField0_ = (bitField0_ & ~0x00000001);
      realName_ = "";
      bitField0_ = (bitField0_ & ~0x00000002);
      userName_ = "";
      bitField0_ = (bitField0_ & ~0x00000004);
      userId_ = 0L;
      bitField0_ = (bitField0_ & ~0x00000008);
      secret_ = "";
      bitField0_ = (bitField0_ & ~0x00000010);
      signinDate_ = "";
      bitField0_ = (bitField0_ & ~0x00000020);
      profileImageUrl_ = "";
      bitField0_ = (bitField0_ & ~0x00000040);
      appName_ = "";
      bitField0_ = (bitField0_ & ~0x00000080);
      deviceName_ = "";
      bitField0_ = (bitField0_ & ~0x00000100);
      deviceScreenSize_ = "";
      bitField0_ = (bitField0_ & ~0x00000200);
      osName_ = "";
      bitField0_ = (bitField0_ & ~0x00000400);
      osVersion_ = "";
      bitField0_ = (bitField0_ & ~0x00000800);
      packageVersion_ = "";
      bitField0_ = (bitField0_ & ~0x00001000);
      packageName_ = "";
      bitField0_ = (bitField0_ & ~0x00002000);
      deviceId_ = "";
      bitField0_ = (bitField0_ & ~0x00004000);
      deviceToken_ = "";
      bitField0_ = (bitField0_ & ~0x00008000);
      apnsEnabled_ = 0;
      bitField0_ = (bitField0_ & ~0x00010000);
      latesAppVers_ = "";
      bitField0_ = (bitField0_ & ~0x00020000);
      localeIdentifier_ = "";
      bitField0_ = (bitField0_ & ~0x00040000);
      latitude_ = 0F;
      bitField0_ = (bitField0_ & ~0x00080000);
      longitude_ = 0F;
      bitField0_ = (bitField0_ & ~0x00100000);
      cityId_ = 0;
      bitField0_ = (bitField0_ & ~0x00200000);
      userKind_ = 0;
      bitField0_ = (bitField0_ & ~0x00400000);
      return this;
    }

    public Builder clone() {
      return create().mergeFrom(buildPartial());
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return android.com.inno.sdk.protobuf.PAppSessionProto.internal_static_PAppSession_descriptor;
    }

    public android.com.inno.sdk.protobuf.PAppSession getDefaultInstanceForType() {
      return android.com.inno.sdk.protobuf.PAppSession.getDefaultInstance();
    }

    public android.com.inno.sdk.protobuf.PAppSession build() {
      android.com.inno.sdk.protobuf.PAppSession result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public android.com.inno.sdk.protobuf.PAppSession buildPartial() {
      android.com.inno.sdk.protobuf.PAppSession result = new android.com.inno.sdk.protobuf.PAppSession(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
        to_bitField0_ |= 0x00000001;
      }
      result.sessionId_ = sessionId_;
      if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
        to_bitField0_ |= 0x00000002;
      }
      result.realName_ = realName_;
      if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
        to_bitField0_ |= 0x00000004;
      }
      result.userName_ = userName_;
      if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
        to_bitField0_ |= 0x00000008;
      }
      result.userId_ = userId_;
      if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
        to_bitField0_ |= 0x00000010;
      }
      result.secret_ = secret_;
      if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
        to_bitField0_ |= 0x00000020;
      }
      result.signinDate_ = signinDate_;
      if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
        to_bitField0_ |= 0x00000040;
      }
      result.profileImageUrl_ = profileImageUrl_;
      if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
        to_bitField0_ |= 0x00000080;
      }
      result.appName_ = appName_;
      if (((from_bitField0_ & 0x00000100) == 0x00000100)) {
        to_bitField0_ |= 0x00000100;
      }
      result.deviceName_ = deviceName_;
      if (((from_bitField0_ & 0x00000200) == 0x00000200)) {
        to_bitField0_ |= 0x00000200;
      }
      result.deviceScreenSize_ = deviceScreenSize_;
      if (((from_bitField0_ & 0x00000400) == 0x00000400)) {
        to_bitField0_ |= 0x00000400;
      }
      result.osName_ = osName_;
      if (((from_bitField0_ & 0x00000800) == 0x00000800)) {
        to_bitField0_ |= 0x00000800;
      }
      result.osVersion_ = osVersion_;
      if (((from_bitField0_ & 0x00001000) == 0x00001000)) {
        to_bitField0_ |= 0x00001000;
      }
      result.packageVersion_ = packageVersion_;
      if (((from_bitField0_ & 0x00002000) == 0x00002000)) {
        to_bitField0_ |= 0x00002000;
      }
      result.packageName_ = packageName_;
      if (((from_bitField0_ & 0x00004000) == 0x00004000)) {
        to_bitField0_ |= 0x00004000;
      }
      result.deviceId_ = deviceId_;
      if (((from_bitField0_ & 0x00008000) == 0x00008000)) {
        to_bitField0_ |= 0x00008000;
      }
      result.deviceToken_ = deviceToken_;
      if (((from_bitField0_ & 0x00010000) == 0x00010000)) {
        to_bitField0_ |= 0x00010000;
      }
      result.apnsEnabled_ = apnsEnabled_;
      if (((from_bitField0_ & 0x00020000) == 0x00020000)) {
        to_bitField0_ |= 0x00020000;
      }
      result.latesAppVers_ = latesAppVers_;
      if (((from_bitField0_ & 0x00040000) == 0x00040000)) {
        to_bitField0_ |= 0x00040000;
      }
      result.localeIdentifier_ = localeIdentifier_;
      if (((from_bitField0_ & 0x00080000) == 0x00080000)) {
        to_bitField0_ |= 0x00080000;
      }
      result.latitude_ = latitude_;
      if (((from_bitField0_ & 0x00100000) == 0x00100000)) {
        to_bitField0_ |= 0x00100000;
      }
      result.longitude_ = longitude_;
      if (((from_bitField0_ & 0x00200000) == 0x00200000)) {
        to_bitField0_ |= 0x00200000;
      }
      result.cityId_ = cityId_;
      if (((from_bitField0_ & 0x00400000) == 0x00400000)) {
        to_bitField0_ |= 0x00400000;
      }
      result.userKind_ = userKind_;
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof android.com.inno.sdk.protobuf.PAppSession) {
        return mergeFrom((android.com.inno.sdk.protobuf.PAppSession)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(android.com.inno.sdk.protobuf.PAppSession other) {
      if (other == android.com.inno.sdk.protobuf.PAppSession.getDefaultInstance()) return this;
      if (other.hasSessionId()) {
        bitField0_ |= 0x00000001;
        sessionId_ = other.sessionId_;
        onChanged();
      }
      if (other.hasRealName()) {
        bitField0_ |= 0x00000002;
        realName_ = other.realName_;
        onChanged();
      }
      if (other.hasUserName()) {
        bitField0_ |= 0x00000004;
        userName_ = other.userName_;
        onChanged();
      }
      if (other.hasUserId()) {
        setUserId(other.getUserId());
      }
      if (other.hasSecret()) {
        bitField0_ |= 0x00000010;
        secret_ = other.secret_;
        onChanged();
      }
      if (other.hasSigninDate()) {
        bitField0_ |= 0x00000020;
        signinDate_ = other.signinDate_;
        onChanged();
      }
      if (other.hasProfileImageUrl()) {
        bitField0_ |= 0x00000040;
        profileImageUrl_ = other.profileImageUrl_;
        onChanged();
      }
      if (other.hasAppName()) {
        bitField0_ |= 0x00000080;
        appName_ = other.appName_;
        onChanged();
      }
      if (other.hasDeviceName()) {
        bitField0_ |= 0x00000100;
        deviceName_ = other.deviceName_;
        onChanged();
      }
      if (other.hasDeviceScreenSize()) {
        bitField0_ |= 0x00000200;
        deviceScreenSize_ = other.deviceScreenSize_;
        onChanged();
      }
      if (other.hasOsName()) {
        bitField0_ |= 0x00000400;
        osName_ = other.osName_;
        onChanged();
      }
      if (other.hasOsVersion()) {
        bitField0_ |= 0x00000800;
        osVersion_ = other.osVersion_;
        onChanged();
      }
      if (other.hasPackageVersion()) {
        bitField0_ |= 0x00001000;
        packageVersion_ = other.packageVersion_;
        onChanged();
      }
      if (other.hasPackageName()) {
        bitField0_ |= 0x00002000;
        packageName_ = other.packageName_;
        onChanged();
      }
      if (other.hasDeviceId()) {
        bitField0_ |= 0x00004000;
        deviceId_ = other.deviceId_;
        onChanged();
      }
      if (other.hasDeviceToken()) {
        bitField0_ |= 0x00008000;
        deviceToken_ = other.deviceToken_;
        onChanged();
      }
      if (other.hasApnsEnabled()) {
        setApnsEnabled(other.getApnsEnabled());
      }
      if (other.hasLatesAppVers()) {
        bitField0_ |= 0x00020000;
        latesAppVers_ = other.latesAppVers_;
        onChanged();
      }
      if (other.hasLocaleIdentifier()) {
        bitField0_ |= 0x00040000;
        localeIdentifier_ = other.localeIdentifier_;
        onChanged();
      }
      if (other.hasLatitude()) {
        setLatitude(other.getLatitude());
      }
      if (other.hasLongitude()) {
        setLongitude(other.getLongitude());
      }
      if (other.hasCityId()) {
        setCityId(other.getCityId());
      }
      if (other.hasUserKind()) {
        setUserKind(other.getUserKind());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      android.com.inno.sdk.protobuf.PAppSession parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (android.com.inno.sdk.protobuf.PAppSession) e.getUnfinishedMessage();
        throw e;
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    // optional string sessionId = 1;
    private java.lang.Object sessionId_ = "";
    /**
     * <code>optional string sessionId = 1;</code>
     */
    public boolean hasSessionId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional string sessionId = 1;</code>
     */
    public java.lang.String getSessionId() {
      java.lang.Object ref = sessionId_;
      if (!(ref instanceof java.lang.String)) {
        java.lang.String s = ((com.google.protobuf.ByteString) ref)
            .toStringUtf8();
        sessionId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string sessionId = 1;</code>
     */
    public com.google.protobuf.ByteString
        getSessionIdBytes() {
      java.lang.Object ref = sessionId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sessionId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string sessionId = 1;</code>
     */
    public Builder setSessionId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
      sessionId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string sessionId = 1;</code>
     */
    public Builder clearSessionId() {
      bitField0_ = (bitField0_ & ~0x00000001);
      sessionId_ = getDefaultInstance().getSessionId();
      onChanged();
      return this;
    }
    /**
     * <code>optional string sessionId = 1;</code>
     */
    public Builder setSessionIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
      sessionId_ = value;
      onChanged();
      return this;
    }

    // optional string realName = 2;
    private java.lang.Object realName_ = "";
    /**
     * <code>optional string realName = 2;</code>
     */
    public boolean hasRealName() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string realName = 2;</code>
     */
    public java.lang.String getRealName() {
      java.lang.Object ref = realName_;
      if (!(ref instanceof java.lang.String)) {
        java.lang.String s = ((com.google.protobuf.ByteString) ref)
            .toStringUtf8();
        realName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string realName = 2;</code>
     */
    public com.google.protobuf.ByteString
        getRealNameBytes() {
      java.lang.Object ref = realName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        realName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string realName = 2;</code>
     */
    public Builder setRealName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
      realName_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string realName = 2;</code>
     */
    public Builder clearRealName() {
      bitField0_ = (bitField0_ & ~0x00000002);
      realName_ = getDefaultInstance().getRealName();
      onChanged();
      return this;
    }
    /**
     * <code>optional string realName = 2;</code>
     */
    public Builder setRealNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
      realName_ = value;
      onChanged();
      return this;
    }

    // optional string userName = 3;
    private java.lang.Object userName_ = "";
    /**
     * <code>optional string userName = 3;</code>
     */
    public boolean hasUserName() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional string userName = 3;</code>
     */
    public java.lang.String getUserName() {
      java.lang.Object ref = userName_;
      if (!(ref instanceof java.lang.String)) {
        java.lang.String s = ((com.google.protobuf.ByteString) ref)
            .toStringUtf8();
        userName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string userName = 3;</code>
     */
    public com.google.protobuf.ByteString
        getUserNameBytes() {
      java.lang.Object ref = userName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        userName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string userName = 3;</code>
     */
    public Builder setUserName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
      userName_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string userName = 3;</code>
     */
    public Builder clearUserName() {
      bitField0_ = (bitField0_ & ~0x00000004);
      userName_ = getDefaultInstance().getUserName();
      onChanged();
      return this;
    }
    /**
     * <code>optional string userName = 3;</code>
     */
    public Builder setUserNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
      userName_ = value;
      onChanged();
      return this;
    }

    // optional int64 userId = 4;
    private long userId_ ;
    /**
     * <code>optional int64 userId = 4;</code>
     */
    public boolean hasUserId() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional int64 userId = 4;</code>
     */
    public long getUserId() {
      return userId_;
    }
    /**
     * <code>optional int64 userId = 4;</code>
     */
    public Builder setUserId(long value) {
      bitField0_ |= 0x00000008;
      userId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional int64 userId = 4;</code>
     */
    public Builder clearUserId() {
      bitField0_ = (bitField0_ & ~0x00000008);
      userId_ = 0L;
      onChanged();
      return this;
    }

    // optional string secret = 5;
    private java.lang.Object secret_ = "";
    /**
     * <code>optional string secret = 5;</code>
     */
    public boolean hasSecret() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional string secret = 5;</code>
     */
    public java.lang.String getSecret() {
      java.lang.Object ref = secret_;
      if (!(ref instanceof java.lang.String)) {
        java.lang.String s = ((com.google.protobuf.ByteString) ref)
            .toStringUtf8();
        secret_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string secret = 5;</code>
     */
    public com.google.protobuf.ByteString
        getSecretBytes() {
      java.lang.Object ref = secret_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        secret_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string secret = 5;</code>
     */
    public Builder setSecret(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
      secret_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string secret = 5;</code>
     */
    public Builder clearSecret() {
      bitField0_ = (bitField0_ & ~0x00000010);
      secret_ = getDefaultInstance().getSecret();
      onChanged();
      return this;
    }
    /**
     * <code>optional string secret = 5;</code>
     */
    public Builder setSecretBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
      secret_ = value;
      onChanged();
      return this;
    }

    // optional string signinDate = 6;
    private java.lang.Object signinDate_ = "";
    /**
     * <code>optional string signinDate = 6;</code>
     */
    public boolean hasSigninDate() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>optional string signinDate = 6;</code>
     */
    public java.lang.String getSigninDate() {
      java.lang.Object ref = signinDate_;
      if (!(ref instanceof java.lang.String)) {
        java.lang.String s = ((com.google.protobuf.ByteString) ref)
            .toStringUtf8();
        signinDate_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string signinDate = 6;</code>
     */
    public com.google.protobuf.ByteString
        getSigninDateBytes() {
      java.lang.Object ref = signinDate_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        signinDate_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string signinDate = 6;</code>
     */
    public Builder setSigninDate(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
      signinDate_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string signinDate = 6;</code>
     */
    public Builder clearSigninDate() {
      bitField0_ = (bitField0_ & ~0x00000020);
      signinDate_ = getDefaultInstance().getSigninDate();
      onChanged();
      return this;
    }
    /**
     * <code>optional string signinDate = 6;</code>
     */
    public Builder setSigninDateBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
      signinDate_ = value;
      onChanged();
      return this;
    }

    // optional string profileImageUrl = 7;
    private java.lang.Object profileImageUrl_ = "";
    /**
     * <code>optional string profileImageUrl = 7;</code>
     */
    public boolean hasProfileImageUrl() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>optional string profileImageUrl = 7;</code>
     */
    public java.lang.String getProfileImageUrl() {
      java.lang.Object ref = profileImageUrl_;
      if (!(ref instanceof java.lang.String)) {
        java.lang.String s = ((com.google.protobuf.ByteString) ref)
            .toStringUtf8();
        profileImageUrl_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string profileImageUrl = 7;</code>
     */
    public com.google.protobuf.ByteString
        getProfileImageUrlBytes() {
      java.lang.Object ref = profileImageUrl_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        profileImageUrl_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string profileImageUrl = 7;</code>
     */
    public Builder setProfileImageUrl(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
      profileImageUrl_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string profileImageUrl = 7;</code>
     */
    public Builder clearProfileImageUrl() {
      bitField0_ = (bitField0_ & ~0x00000040);
      profileImageUrl_ = getDefaultInstance().getProfileImageUrl();
      onChanged();
      return this;
    }
    /**
     * <code>optional string profileImageUrl = 7;</code>
     */
    public Builder setProfileImageUrlBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
      profileImageUrl_ = value;
      onChanged();
      return this;
    }

    // optional string appName = 8;
    private java.lang.Object appName_ = "";
    /**
     * <code>optional string appName = 8;</code>
     */
    public boolean hasAppName() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    /**
     * <code>optional string appName = 8;</code>
     */
    public java.lang.String getAppName() {
      java.lang.Object ref = appName_;
      if (!(ref instanceof java.lang.String)) {
        java.lang.String s = ((com.google.protobuf.ByteString) ref)
            .toStringUtf8();
        appName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string appName = 8;</code>
     */
    public com.google.protobuf.ByteString
        getAppNameBytes() {
      java.lang.Object ref = appName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        appName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string appName = 8;</code>
     */
    public Builder setAppName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000080;
      appName_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string appName = 8;</code>
     */
    public Builder clearAppName() {
      bitField0_ = (bitField0_ & ~0x00000080);
      appName_ = getDefaultInstance().getAppName();
      onChanged();
      return this;
    }
    /**
     * <code>optional string appName = 8;</code>
     */
    public Builder setAppNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000080;
      appName_ = value;
      onChanged();
      return this;
    }

    // optional string deviceName = 9;
    private java.lang.Object deviceName_ = "";
    /**
     * <code>optional string deviceName = 9;</code>
     */
    public boolean hasDeviceName() {
      return ((bitField0_ & 0x00000100) == 0x00000100);
    }
    /**
     * <code>optional string deviceName = 9;</code>
     */
    public java.lang.String getDeviceName() {
      java.lang.Object ref = deviceName_;
      if (!(ref instanceof java.lang.String)) {
        java.lang.String s = ((com.google.protobuf.ByteString) ref)
            .toStringUtf8();
        deviceName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string deviceName = 9;</code>
     */
    public com.google.protobuf.ByteString
        getDeviceNameBytes() {
      java.lang.Object ref = deviceName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        deviceName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string deviceName = 9;</code>
     */
    public Builder setDeviceName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000100;
      deviceName_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string deviceName = 9;</code>
     */
    public Builder clearDeviceName() {
      bitField0_ = (bitField0_ & ~0x00000100);
      deviceName_ = getDefaultInstance().getDeviceName();
      onChanged();
      return this;
    }
    /**
     * <code>optional string deviceName = 9;</code>
     */
    public Builder setDeviceNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000100;
      deviceName_ = value;
      onChanged();
      return this;
    }

    // optional string deviceScreenSize = 10;
    private java.lang.Object deviceScreenSize_ = "";
    /**
     * <code>optional string deviceScreenSize = 10;</code>
     */
    public boolean hasDeviceScreenSize() {
      return ((bitField0_ & 0x00000200) == 0x00000200);
    }
    /**
     * <code>optional string deviceScreenSize = 10;</code>
     */
    public java.lang.String getDeviceScreenSize() {
      java.lang.Object ref = deviceScreenSize_;
      if (!(ref instanceof java.lang.String)) {
        java.lang.String s = ((com.google.protobuf.ByteString) ref)
            .toStringUtf8();
        deviceScreenSize_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string deviceScreenSize = 10;</code>
     */
    public com.google.protobuf.ByteString
        getDeviceScreenSizeBytes() {
      java.lang.Object ref = deviceScreenSize_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        deviceScreenSize_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string deviceScreenSize = 10;</code>
     */
    public Builder setDeviceScreenSize(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000200;
      deviceScreenSize_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string deviceScreenSize = 10;</code>
     */
    public Builder clearDeviceScreenSize() {
      bitField0_ = (bitField0_ & ~0x00000200);
      deviceScreenSize_ = getDefaultInstance().getDeviceScreenSize();
      onChanged();
      return this;
    }
    /**
     * <code>optional string deviceScreenSize = 10;</code>
     */
    public Builder setDeviceScreenSizeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000200;
      deviceScreenSize_ = value;
      onChanged();
      return this;
    }

    // optional string osName = 11;
    private java.lang.Object osName_ = "";
    /**
     * <code>optional string osName = 11;</code>
     */
    public boolean hasOsName() {
      return ((bitField0_ & 0x00000400) == 0x00000400);
    }
    /**
     * <code>optional string osName = 11;</code>
     */
    public java.lang.String getOsName() {
      java.lang.Object ref = osName_;
      if (!(ref instanceof java.lang.String)) {
        java.lang.String s = ((com.google.protobuf.ByteString) ref)
            .toStringUtf8();
        osName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string osName = 11;</code>
     */
    public com.google.protobuf.ByteString
        getOsNameBytes() {
      java.lang.Object ref = osName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        osName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string osName = 11;</code>
     */
    public Builder setOsName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000400;
      osName_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string osName = 11;</code>
     */
    public Builder clearOsName() {
      bitField0_ = (bitField0_ & ~0x00000400);
      osName_ = getDefaultInstance().getOsName();
      onChanged();
      return this;
    }
    /**
     * <code>optional string osName = 11;</code>
     */
    public Builder setOsNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000400;
      osName_ = value;
      onChanged();
      return this;
    }

    // optional string osVersion = 12;
    private java.lang.Object osVersion_ = "";
    /**
     * <code>optional string osVersion = 12;</code>
     */
    public boolean hasOsVersion() {
      return ((bitField0_ & 0x00000800) == 0x00000800);
    }
    /**
     * <code>optional string osVersion = 12;</code>
     */
    public java.lang.String getOsVersion() {
      java.lang.Object ref = osVersion_;
      if (!(ref instanceof java.lang.String)) {
        java.lang.String s = ((com.google.protobuf.ByteString) ref)
            .toStringUtf8();
        osVersion_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string osVersion = 12;</code>
     */
    public com.google.protobuf.ByteString
        getOsVersionBytes() {
      java.lang.Object ref = osVersion_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        osVersion_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string osVersion = 12;</code>
     */
    public Builder setOsVersion(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000800;
      osVersion_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string osVersion = 12;</code>
     */
    public Builder clearOsVersion() {
      bitField0_ = (bitField0_ & ~0x00000800);
      osVersion_ = getDefaultInstance().getOsVersion();
      onChanged();
      return this;
    }
    /**
     * <code>optional string osVersion = 12;</code>
     */
    public Builder setOsVersionBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000800;
      osVersion_ = value;
      onChanged();
      return this;
    }

    // optional string packageVersion = 13;
    private java.lang.Object packageVersion_ = "";
    /**
     * <code>optional string packageVersion = 13;</code>
     */
    public boolean hasPackageVersion() {
      return ((bitField0_ & 0x00001000) == 0x00001000);
    }
    /**
     * <code>optional string packageVersion = 13;</code>
     */
    public java.lang.String getPackageVersion() {
      java.lang.Object ref = packageVersion_;
      if (!(ref instanceof java.lang.String)) {
        java.lang.String s = ((com.google.protobuf.ByteString) ref)
            .toStringUtf8();
        packageVersion_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string packageVersion = 13;</code>
     */
    public com.google.protobuf.ByteString
        getPackageVersionBytes() {
      java.lang.Object ref = packageVersion_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        packageVersion_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string packageVersion = 13;</code>
     */
    public Builder setPackageVersion(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00001000;
      packageVersion_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string packageVersion = 13;</code>
     */
    public Builder clearPackageVersion() {
      bitField0_ = (bitField0_ & ~0x00001000);
      packageVersion_ = getDefaultInstance().getPackageVersion();
      onChanged();
      return this;
    }
    /**
     * <code>optional string packageVersion = 13;</code>
     */
    public Builder setPackageVersionBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00001000;
      packageVersion_ = value;
      onChanged();
      return this;
    }

    // optional string packageName = 14;
    private java.lang.Object packageName_ = "";
    /**
     * <code>optional string packageName = 14;</code>
     */
    public boolean hasPackageName() {
      return ((bitField0_ & 0x00002000) == 0x00002000);
    }
    /**
     * <code>optional string packageName = 14;</code>
     */
    public java.lang.String getPackageName() {
      java.lang.Object ref = packageName_;
      if (!(ref instanceof java.lang.String)) {
        java.lang.String s = ((com.google.protobuf.ByteString) ref)
            .toStringUtf8();
        packageName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string packageName = 14;</code>
     */
    public com.google.protobuf.ByteString
        getPackageNameBytes() {
      java.lang.Object ref = packageName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        packageName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string packageName = 14;</code>
     */
    public Builder setPackageName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00002000;
      packageName_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string packageName = 14;</code>
     */
    public Builder clearPackageName() {
      bitField0_ = (bitField0_ & ~0x00002000);
      packageName_ = getDefaultInstance().getPackageName();
      onChanged();
      return this;
    }
    /**
     * <code>optional string packageName = 14;</code>
     */
    public Builder setPackageNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00002000;
      packageName_ = value;
      onChanged();
      return this;
    }

    // optional string deviceId = 15;
    private java.lang.Object deviceId_ = "";
    /**
     * <code>optional string deviceId = 15;</code>
     */
    public boolean hasDeviceId() {
      return ((bitField0_ & 0x00004000) == 0x00004000);
    }
    /**
     * <code>optional string deviceId = 15;</code>
     */
    public java.lang.String getDeviceId() {
      java.lang.Object ref = deviceId_;
      if (!(ref instanceof java.lang.String)) {
        java.lang.String s = ((com.google.protobuf.ByteString) ref)
            .toStringUtf8();
        deviceId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string deviceId = 15;</code>
     */
    public com.google.protobuf.ByteString
        getDeviceIdBytes() {
      java.lang.Object ref = deviceId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        deviceId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string deviceId = 15;</code>
     */
    public Builder setDeviceId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00004000;
      deviceId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string deviceId = 15;</code>
     */
    public Builder clearDeviceId() {
      bitField0_ = (bitField0_ & ~0x00004000);
      deviceId_ = getDefaultInstance().getDeviceId();
      onChanged();
      return this;
    }
    /**
     * <code>optional string deviceId = 15;</code>
     */
    public Builder setDeviceIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00004000;
      deviceId_ = value;
      onChanged();
      return this;
    }

    // optional string deviceToken = 16;
    private java.lang.Object deviceToken_ = "";
    /**
     * <code>optional string deviceToken = 16;</code>
     */
    public boolean hasDeviceToken() {
      return ((bitField0_ & 0x00008000) == 0x00008000);
    }
    /**
     * <code>optional string deviceToken = 16;</code>
     */
    public java.lang.String getDeviceToken() {
      java.lang.Object ref = deviceToken_;
      if (!(ref instanceof java.lang.String)) {
        java.lang.String s = ((com.google.protobuf.ByteString) ref)
            .toStringUtf8();
        deviceToken_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string deviceToken = 16;</code>
     */
    public com.google.protobuf.ByteString
        getDeviceTokenBytes() {
      java.lang.Object ref = deviceToken_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        deviceToken_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string deviceToken = 16;</code>
     */
    public Builder setDeviceToken(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00008000;
      deviceToken_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string deviceToken = 16;</code>
     */
    public Builder clearDeviceToken() {
      bitField0_ = (bitField0_ & ~0x00008000);
      deviceToken_ = getDefaultInstance().getDeviceToken();
      onChanged();
      return this;
    }
    /**
     * <code>optional string deviceToken = 16;</code>
     */
    public Builder setDeviceTokenBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00008000;
      deviceToken_ = value;
      onChanged();
      return this;
    }

    // optional int32 apnsEnabled = 17;
    private int apnsEnabled_ ;
    /**
     * <code>optional int32 apnsEnabled = 17;</code>
     */
    public boolean hasApnsEnabled() {
      return ((bitField0_ & 0x00010000) == 0x00010000);
    }
    /**
     * <code>optional int32 apnsEnabled = 17;</code>
     */
    public int getApnsEnabled() {
      return apnsEnabled_;
    }
    /**
     * <code>optional int32 apnsEnabled = 17;</code>
     */
    public Builder setApnsEnabled(int value) {
      bitField0_ |= 0x00010000;
      apnsEnabled_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional int32 apnsEnabled = 17;</code>
     */
    public Builder clearApnsEnabled() {
      bitField0_ = (bitField0_ & ~0x00010000);
      apnsEnabled_ = 0;
      onChanged();
      return this;
    }

    // optional string latesAppVers = 18;
    private java.lang.Object latesAppVers_ = "";
    /**
     * <code>optional string latesAppVers = 18;</code>
     */
    public boolean hasLatesAppVers() {
      return ((bitField0_ & 0x00020000) == 0x00020000);
    }
    /**
     * <code>optional string latesAppVers = 18;</code>
     */
    public java.lang.String getLatesAppVers() {
      java.lang.Object ref = latesAppVers_;
      if (!(ref instanceof java.lang.String)) {
        java.lang.String s = ((com.google.protobuf.ByteString) ref)
            .toStringUtf8();
        latesAppVers_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string latesAppVers = 18;</code>
     */
    public com.google.protobuf.ByteString
        getLatesAppVersBytes() {
      java.lang.Object ref = latesAppVers_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        latesAppVers_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string latesAppVers = 18;</code>
     */
    public Builder setLatesAppVers(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00020000;
      latesAppVers_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string latesAppVers = 18;</code>
     */
    public Builder clearLatesAppVers() {
      bitField0_ = (bitField0_ & ~0x00020000);
      latesAppVers_ = getDefaultInstance().getLatesAppVers();
      onChanged();
      return this;
    }
    /**
     * <code>optional string latesAppVers = 18;</code>
     */
    public Builder setLatesAppVersBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00020000;
      latesAppVers_ = value;
      onChanged();
      return this;
    }

    // optional string localeIdentifier = 19;
    private java.lang.Object localeIdentifier_ = "";
    /**
     * <code>optional string localeIdentifier = 19;</code>
     */
    public boolean hasLocaleIdentifier() {
      return ((bitField0_ & 0x00040000) == 0x00040000);
    }
    /**
     * <code>optional string localeIdentifier = 19;</code>
     */
    public java.lang.String getLocaleIdentifier() {
      java.lang.Object ref = localeIdentifier_;
      if (!(ref instanceof java.lang.String)) {
        java.lang.String s = ((com.google.protobuf.ByteString) ref)
            .toStringUtf8();
        localeIdentifier_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string localeIdentifier = 19;</code>
     */
    public com.google.protobuf.ByteString
        getLocaleIdentifierBytes() {
      java.lang.Object ref = localeIdentifier_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        localeIdentifier_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string localeIdentifier = 19;</code>
     */
    public Builder setLocaleIdentifier(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00040000;
      localeIdentifier_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string localeIdentifier = 19;</code>
     */
    public Builder clearLocaleIdentifier() {
      bitField0_ = (bitField0_ & ~0x00040000);
      localeIdentifier_ = getDefaultInstance().getLocaleIdentifier();
      onChanged();
      return this;
    }
    /**
     * <code>optional string localeIdentifier = 19;</code>
     */
    public Builder setLocaleIdentifierBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00040000;
      localeIdentifier_ = value;
      onChanged();
      return this;
    }

    // optional float latitude = 20;
    private float latitude_ ;
    /**
     * <code>optional float latitude = 20;</code>
     */
    public boolean hasLatitude() {
      return ((bitField0_ & 0x00080000) == 0x00080000);
    }
    /**
     * <code>optional float latitude = 20;</code>
     */
    public float getLatitude() {
      return latitude_;
    }
    /**
     * <code>optional float latitude = 20;</code>
     */
    public Builder setLatitude(float value) {
      bitField0_ |= 0x00080000;
      latitude_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional float latitude = 20;</code>
     */
    public Builder clearLatitude() {
      bitField0_ = (bitField0_ & ~0x00080000);
      latitude_ = 0F;
      onChanged();
      return this;
    }

    // optional float longitude = 21;
    private float longitude_ ;
    /**
     * <code>optional float longitude = 21;</code>
     */
    public boolean hasLongitude() {
      return ((bitField0_ & 0x00100000) == 0x00100000);
    }
    /**
     * <code>optional float longitude = 21;</code>
     */
    public float getLongitude() {
      return longitude_;
    }
    /**
     * <code>optional float longitude = 21;</code>
     */
    public Builder setLongitude(float value) {
      bitField0_ |= 0x00100000;
      longitude_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional float longitude = 21;</code>
     */
    public Builder clearLongitude() {
      bitField0_ = (bitField0_ & ~0x00100000);
      longitude_ = 0F;
      onChanged();
      return this;
    }

    // optional int32 cityId = 22;
    private int cityId_ ;
    /**
     * <code>optional int32 cityId = 22;</code>
     */
    public boolean hasCityId() {
      return ((bitField0_ & 0x00200000) == 0x00200000);
    }
    /**
     * <code>optional int32 cityId = 22;</code>
     */
    public int getCityId() {
      return cityId_;
    }
    /**
     * <code>optional int32 cityId = 22;</code>
     */
    public Builder setCityId(int value) {
      bitField0_ |= 0x00200000;
      cityId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional int32 cityId = 22;</code>
     */
    public Builder clearCityId() {
      bitField0_ = (bitField0_ & ~0x00200000);
      cityId_ = 0;
      onChanged();
      return this;
    }

    // optional int32 userKind = 23;
    private int userKind_ ;
    /**
     * <code>optional int32 userKind = 23;</code>
     */
    public boolean hasUserKind() {
      return ((bitField0_ & 0x00400000) == 0x00400000);
    }
    /**
     * <code>optional int32 userKind = 23;</code>
     */
    public int getUserKind() {
      return userKind_;
    }
    /**
     * <code>optional int32 userKind = 23;</code>
     */
    public Builder setUserKind(int value) {
      bitField0_ |= 0x00400000;
      userKind_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional int32 userKind = 23;</code>
     */
    public Builder clearUserKind() {
      bitField0_ = (bitField0_ & ~0x00400000);
      userKind_ = 0;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:PAppSession)
  }

  static {
    defaultInstance = new PAppSession(true);
    defaultInstance.initFields();
  }

  // @@protoc_insertion_point(class_scope:PAppSession)
}

